# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

# Default values for nvd-scanner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scanner:
  api_token: "my_token"
  heureka_url: "heureka.com"
  schedule: "0 * * * *"
  nvd:
    api_url: ""
    api_key: ""
    results_per_page: 2000
    # can be used to specify the range from which the NVD data should be fetched, by default is fetched from last day
    start_date: ""
    end_date: ""

image:
  repository: ghcr.io/cloudoperators/heureka-scanner-nvd
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
