// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.wdf.sap.corp/cc/heureka/internal/entity"
)

// MockHeureka is an autogenerated mock type for the Heureka type
type MockHeureka struct {
	mock.Mock
}

type MockHeureka_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHeureka) EXPECT() *MockHeureka_Expecter {
	return &MockHeureka_Expecter{mock: &_m.Mock}
}

// CreateActivity provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateActivity(_a0 *entity.Activity) (*entity.Activity, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateActivity")
	}

	var r0 *entity.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Activity) (*entity.Activity, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Activity) *entity.Activity); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Activity) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateActivity'
type MockHeureka_CreateActivity_Call struct {
	*mock.Call
}

// CreateActivity is a helper method to define mock.On call
//   - _a0 *entity.Activity
func (_e *MockHeureka_Expecter) CreateActivity(_a0 interface{}) *MockHeureka_CreateActivity_Call {
	return &MockHeureka_CreateActivity_Call{Call: _e.mock.On("CreateActivity", _a0)}
}

func (_c *MockHeureka_CreateActivity_Call) Run(run func(_a0 *entity.Activity)) *MockHeureka_CreateActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Activity))
	})
	return _c
}

func (_c *MockHeureka_CreateActivity_Call) Return(_a0 *entity.Activity, _a1 error) *MockHeureka_CreateActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateActivity_Call) RunAndReturn(run func(*entity.Activity) (*entity.Activity, error)) *MockHeureka_CreateActivity_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComponent provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateComponent(_a0 *entity.Component) (*entity.Component, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateComponent")
	}

	var r0 *entity.Component
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Component) (*entity.Component, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Component) *entity.Component); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Component)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Component) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComponent'
type MockHeureka_CreateComponent_Call struct {
	*mock.Call
}

// CreateComponent is a helper method to define mock.On call
//   - _a0 *entity.Component
func (_e *MockHeureka_Expecter) CreateComponent(_a0 interface{}) *MockHeureka_CreateComponent_Call {
	return &MockHeureka_CreateComponent_Call{Call: _e.mock.On("CreateComponent", _a0)}
}

func (_c *MockHeureka_CreateComponent_Call) Run(run func(_a0 *entity.Component)) *MockHeureka_CreateComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Component))
	})
	return _c
}

func (_c *MockHeureka_CreateComponent_Call) Return(_a0 *entity.Component, _a1 error) *MockHeureka_CreateComponent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateComponent_Call) RunAndReturn(run func(*entity.Component) (*entity.Component, error)) *MockHeureka_CreateComponent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComponentInstance provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateComponentInstance(_a0 *entity.ComponentInstance) (*entity.ComponentInstance, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateComponentInstance")
	}

	var r0 *entity.ComponentInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.ComponentInstance) (*entity.ComponentInstance, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.ComponentInstance) *entity.ComponentInstance); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ComponentInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.ComponentInstance) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateComponentInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComponentInstance'
type MockHeureka_CreateComponentInstance_Call struct {
	*mock.Call
}

// CreateComponentInstance is a helper method to define mock.On call
//   - _a0 *entity.ComponentInstance
func (_e *MockHeureka_Expecter) CreateComponentInstance(_a0 interface{}) *MockHeureka_CreateComponentInstance_Call {
	return &MockHeureka_CreateComponentInstance_Call{Call: _e.mock.On("CreateComponentInstance", _a0)}
}

func (_c *MockHeureka_CreateComponentInstance_Call) Run(run func(_a0 *entity.ComponentInstance)) *MockHeureka_CreateComponentInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.ComponentInstance))
	})
	return _c
}

func (_c *MockHeureka_CreateComponentInstance_Call) Return(_a0 *entity.ComponentInstance, _a1 error) *MockHeureka_CreateComponentInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateComponentInstance_Call) RunAndReturn(run func(*entity.ComponentInstance) (*entity.ComponentInstance, error)) *MockHeureka_CreateComponentInstance_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComponentVersion provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateComponentVersion(_a0 *entity.ComponentVersion) (*entity.ComponentVersion, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateComponentVersion")
	}

	var r0 *entity.ComponentVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.ComponentVersion) (*entity.ComponentVersion, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.ComponentVersion) *entity.ComponentVersion); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ComponentVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.ComponentVersion) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateComponentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComponentVersion'
type MockHeureka_CreateComponentVersion_Call struct {
	*mock.Call
}

// CreateComponentVersion is a helper method to define mock.On call
//   - _a0 *entity.ComponentVersion
func (_e *MockHeureka_Expecter) CreateComponentVersion(_a0 interface{}) *MockHeureka_CreateComponentVersion_Call {
	return &MockHeureka_CreateComponentVersion_Call{Call: _e.mock.On("CreateComponentVersion", _a0)}
}

func (_c *MockHeureka_CreateComponentVersion_Call) Run(run func(_a0 *entity.ComponentVersion)) *MockHeureka_CreateComponentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.ComponentVersion))
	})
	return _c
}

func (_c *MockHeureka_CreateComponentVersion_Call) Return(_a0 *entity.ComponentVersion, _a1 error) *MockHeureka_CreateComponentVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateComponentVersion_Call) RunAndReturn(run func(*entity.ComponentVersion) (*entity.ComponentVersion, error)) *MockHeureka_CreateComponentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvidence provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateEvidence(_a0 *entity.Evidence) (*entity.Evidence, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvidence")
	}

	var r0 *entity.Evidence
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Evidence) (*entity.Evidence, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Evidence) *entity.Evidence); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Evidence)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Evidence) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvidence'
type MockHeureka_CreateEvidence_Call struct {
	*mock.Call
}

// CreateEvidence is a helper method to define mock.On call
//   - _a0 *entity.Evidence
func (_e *MockHeureka_Expecter) CreateEvidence(_a0 interface{}) *MockHeureka_CreateEvidence_Call {
	return &MockHeureka_CreateEvidence_Call{Call: _e.mock.On("CreateEvidence", _a0)}
}

func (_c *MockHeureka_CreateEvidence_Call) Run(run func(_a0 *entity.Evidence)) *MockHeureka_CreateEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Evidence))
	})
	return _c
}

func (_c *MockHeureka_CreateEvidence_Call) Return(_a0 *entity.Evidence, _a1 error) *MockHeureka_CreateEvidence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateEvidence_Call) RunAndReturn(run func(*entity.Evidence) (*entity.Evidence, error)) *MockHeureka_CreateEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIssue provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateIssue(_a0 *entity.Issue) (*entity.Issue, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateIssue")
	}

	var r0 *entity.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Issue) (*entity.Issue, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Issue) *entity.Issue); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Issue) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIssue'
type MockHeureka_CreateIssue_Call struct {
	*mock.Call
}

// CreateIssue is a helper method to define mock.On call
//   - _a0 *entity.Issue
func (_e *MockHeureka_Expecter) CreateIssue(_a0 interface{}) *MockHeureka_CreateIssue_Call {
	return &MockHeureka_CreateIssue_Call{Call: _e.mock.On("CreateIssue", _a0)}
}

func (_c *MockHeureka_CreateIssue_Call) Run(run func(_a0 *entity.Issue)) *MockHeureka_CreateIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Issue))
	})
	return _c
}

func (_c *MockHeureka_CreateIssue_Call) Return(_a0 *entity.Issue, _a1 error) *MockHeureka_CreateIssue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateIssue_Call) RunAndReturn(run func(*entity.Issue) (*entity.Issue, error)) *MockHeureka_CreateIssue_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIssueMatch provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateIssueMatch(_a0 *entity.IssueMatch) (*entity.IssueMatch, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateIssueMatch")
	}

	var r0 *entity.IssueMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueMatch) (*entity.IssueMatch, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueMatch) *entity.IssueMatch); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.IssueMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueMatch) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateIssueMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIssueMatch'
type MockHeureka_CreateIssueMatch_Call struct {
	*mock.Call
}

// CreateIssueMatch is a helper method to define mock.On call
//   - _a0 *entity.IssueMatch
func (_e *MockHeureka_Expecter) CreateIssueMatch(_a0 interface{}) *MockHeureka_CreateIssueMatch_Call {
	return &MockHeureka_CreateIssueMatch_Call{Call: _e.mock.On("CreateIssueMatch", _a0)}
}

func (_c *MockHeureka_CreateIssueMatch_Call) Run(run func(_a0 *entity.IssueMatch)) *MockHeureka_CreateIssueMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueMatch))
	})
	return _c
}

func (_c *MockHeureka_CreateIssueMatch_Call) Return(_a0 *entity.IssueMatch, _a1 error) *MockHeureka_CreateIssueMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateIssueMatch_Call) RunAndReturn(run func(*entity.IssueMatch) (*entity.IssueMatch, error)) *MockHeureka_CreateIssueMatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIssueRepository provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateIssueRepository(_a0 *entity.IssueRepository) (*entity.IssueRepository, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateIssueRepository")
	}

	var r0 *entity.IssueRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueRepository) (*entity.IssueRepository, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueRepository) *entity.IssueRepository); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.IssueRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueRepository) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateIssueRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIssueRepository'
type MockHeureka_CreateIssueRepository_Call struct {
	*mock.Call
}

// CreateIssueRepository is a helper method to define mock.On call
//   - _a0 *entity.IssueRepository
func (_e *MockHeureka_Expecter) CreateIssueRepository(_a0 interface{}) *MockHeureka_CreateIssueRepository_Call {
	return &MockHeureka_CreateIssueRepository_Call{Call: _e.mock.On("CreateIssueRepository", _a0)}
}

func (_c *MockHeureka_CreateIssueRepository_Call) Run(run func(_a0 *entity.IssueRepository)) *MockHeureka_CreateIssueRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueRepository))
	})
	return _c
}

func (_c *MockHeureka_CreateIssueRepository_Call) Return(_a0 *entity.IssueRepository, _a1 error) *MockHeureka_CreateIssueRepository_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateIssueRepository_Call) RunAndReturn(run func(*entity.IssueRepository) (*entity.IssueRepository, error)) *MockHeureka_CreateIssueRepository_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIssueVariant provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateIssueVariant(_a0 *entity.IssueVariant) (*entity.IssueVariant, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateIssueVariant")
	}

	var r0 *entity.IssueVariant
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueVariant) (*entity.IssueVariant, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueVariant) *entity.IssueVariant); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.IssueVariant)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueVariant) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateIssueVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIssueVariant'
type MockHeureka_CreateIssueVariant_Call struct {
	*mock.Call
}

// CreateIssueVariant is a helper method to define mock.On call
//   - _a0 *entity.IssueVariant
func (_e *MockHeureka_Expecter) CreateIssueVariant(_a0 interface{}) *MockHeureka_CreateIssueVariant_Call {
	return &MockHeureka_CreateIssueVariant_Call{Call: _e.mock.On("CreateIssueVariant", _a0)}
}

func (_c *MockHeureka_CreateIssueVariant_Call) Run(run func(_a0 *entity.IssueVariant)) *MockHeureka_CreateIssueVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueVariant))
	})
	return _c
}

func (_c *MockHeureka_CreateIssueVariant_Call) Return(_a0 *entity.IssueVariant, _a1 error) *MockHeureka_CreateIssueVariant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateIssueVariant_Call) RunAndReturn(run func(*entity.IssueVariant) (*entity.IssueVariant, error)) *MockHeureka_CreateIssueVariant_Call {
	_c.Call.Return(run)
	return _c
}

// CreateService provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateService(_a0 *entity.Service) (*entity.Service, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateService")
	}

	var r0 *entity.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Service) (*entity.Service, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Service) *entity.Service); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Service) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateService'
type MockHeureka_CreateService_Call struct {
	*mock.Call
}

// CreateService is a helper method to define mock.On call
//   - _a0 *entity.Service
func (_e *MockHeureka_Expecter) CreateService(_a0 interface{}) *MockHeureka_CreateService_Call {
	return &MockHeureka_CreateService_Call{Call: _e.mock.On("CreateService", _a0)}
}

func (_c *MockHeureka_CreateService_Call) Run(run func(_a0 *entity.Service)) *MockHeureka_CreateService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Service))
	})
	return _c
}

func (_c *MockHeureka_CreateService_Call) Return(_a0 *entity.Service, _a1 error) *MockHeureka_CreateService_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateService_Call) RunAndReturn(run func(*entity.Service) (*entity.Service, error)) *MockHeureka_CreateService_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSupportGroup provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateSupportGroup(_a0 *entity.SupportGroup) (*entity.SupportGroup, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateSupportGroup")
	}

	var r0 *entity.SupportGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.SupportGroup) (*entity.SupportGroup, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.SupportGroup) *entity.SupportGroup); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SupportGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.SupportGroup) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateSupportGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSupportGroup'
type MockHeureka_CreateSupportGroup_Call struct {
	*mock.Call
}

// CreateSupportGroup is a helper method to define mock.On call
//   - _a0 *entity.SupportGroup
func (_e *MockHeureka_Expecter) CreateSupportGroup(_a0 interface{}) *MockHeureka_CreateSupportGroup_Call {
	return &MockHeureka_CreateSupportGroup_Call{Call: _e.mock.On("CreateSupportGroup", _a0)}
}

func (_c *MockHeureka_CreateSupportGroup_Call) Run(run func(_a0 *entity.SupportGroup)) *MockHeureka_CreateSupportGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.SupportGroup))
	})
	return _c
}

func (_c *MockHeureka_CreateSupportGroup_Call) Return(_a0 *entity.SupportGroup, _a1 error) *MockHeureka_CreateSupportGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateSupportGroup_Call) RunAndReturn(run func(*entity.SupportGroup) (*entity.SupportGroup, error)) *MockHeureka_CreateSupportGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: _a0
func (_m *MockHeureka) CreateUser(_a0 *entity.User) (*entity.User, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.User) (*entity.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.User) *entity.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockHeureka_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - _a0 *entity.User
func (_e *MockHeureka_Expecter) CreateUser(_a0 interface{}) *MockHeureka_CreateUser_Call {
	return &MockHeureka_CreateUser_Call{Call: _e.mock.On("CreateUser", _a0)}
}

func (_c *MockHeureka_CreateUser_Call) Run(run func(_a0 *entity.User)) *MockHeureka_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.User))
	})
	return _c
}

func (_c *MockHeureka_CreateUser_Call) Return(_a0 *entity.User, _a1 error) *MockHeureka_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_CreateUser_Call) RunAndReturn(run func(*entity.User) (*entity.User, error)) *MockHeureka_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActivity provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteActivity(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActivity'
type MockHeureka_DeleteActivity_Call struct {
	*mock.Call
}

// DeleteActivity is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteActivity(_a0 interface{}) *MockHeureka_DeleteActivity_Call {
	return &MockHeureka_DeleteActivity_Call{Call: _e.mock.On("DeleteActivity", _a0)}
}

func (_c *MockHeureka_DeleteActivity_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteActivity_Call) Return(_a0 error) *MockHeureka_DeleteActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteActivity_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteActivity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComponent provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteComponent(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComponent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComponent'
type MockHeureka_DeleteComponent_Call struct {
	*mock.Call
}

// DeleteComponent is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteComponent(_a0 interface{}) *MockHeureka_DeleteComponent_Call {
	return &MockHeureka_DeleteComponent_Call{Call: _e.mock.On("DeleteComponent", _a0)}
}

func (_c *MockHeureka_DeleteComponent_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteComponent_Call) Return(_a0 error) *MockHeureka_DeleteComponent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteComponent_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteComponent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComponentInstance provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteComponentInstance(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComponentInstance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteComponentInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComponentInstance'
type MockHeureka_DeleteComponentInstance_Call struct {
	*mock.Call
}

// DeleteComponentInstance is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteComponentInstance(_a0 interface{}) *MockHeureka_DeleteComponentInstance_Call {
	return &MockHeureka_DeleteComponentInstance_Call{Call: _e.mock.On("DeleteComponentInstance", _a0)}
}

func (_c *MockHeureka_DeleteComponentInstance_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteComponentInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteComponentInstance_Call) Return(_a0 error) *MockHeureka_DeleteComponentInstance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteComponentInstance_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteComponentInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComponentVersion provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteComponentVersion(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComponentVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteComponentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComponentVersion'
type MockHeureka_DeleteComponentVersion_Call struct {
	*mock.Call
}

// DeleteComponentVersion is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteComponentVersion(_a0 interface{}) *MockHeureka_DeleteComponentVersion_Call {
	return &MockHeureka_DeleteComponentVersion_Call{Call: _e.mock.On("DeleteComponentVersion", _a0)}
}

func (_c *MockHeureka_DeleteComponentVersion_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteComponentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteComponentVersion_Call) Return(_a0 error) *MockHeureka_DeleteComponentVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteComponentVersion_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteComponentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvidence provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteEvidence(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvidence")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvidence'
type MockHeureka_DeleteEvidence_Call struct {
	*mock.Call
}

// DeleteEvidence is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteEvidence(_a0 interface{}) *MockHeureka_DeleteEvidence_Call {
	return &MockHeureka_DeleteEvidence_Call{Call: _e.mock.On("DeleteEvidence", _a0)}
}

func (_c *MockHeureka_DeleteEvidence_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteEvidence_Call) Return(_a0 error) *MockHeureka_DeleteEvidence_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteEvidence_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssue provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteIssue(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssue'
type MockHeureka_DeleteIssue_Call struct {
	*mock.Call
}

// DeleteIssue is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteIssue(_a0 interface{}) *MockHeureka_DeleteIssue_Call {
	return &MockHeureka_DeleteIssue_Call{Call: _e.mock.On("DeleteIssue", _a0)}
}

func (_c *MockHeureka_DeleteIssue_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteIssue_Call) Return(_a0 error) *MockHeureka_DeleteIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteIssue_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteIssue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssueMatch provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteIssueMatch(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssueMatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteIssueMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssueMatch'
type MockHeureka_DeleteIssueMatch_Call struct {
	*mock.Call
}

// DeleteIssueMatch is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteIssueMatch(_a0 interface{}) *MockHeureka_DeleteIssueMatch_Call {
	return &MockHeureka_DeleteIssueMatch_Call{Call: _e.mock.On("DeleteIssueMatch", _a0)}
}

func (_c *MockHeureka_DeleteIssueMatch_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteIssueMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteIssueMatch_Call) Return(_a0 error) *MockHeureka_DeleteIssueMatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteIssueMatch_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteIssueMatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssueRepository provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteIssueRepository(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssueRepository")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteIssueRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssueRepository'
type MockHeureka_DeleteIssueRepository_Call struct {
	*mock.Call
}

// DeleteIssueRepository is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteIssueRepository(_a0 interface{}) *MockHeureka_DeleteIssueRepository_Call {
	return &MockHeureka_DeleteIssueRepository_Call{Call: _e.mock.On("DeleteIssueRepository", _a0)}
}

func (_c *MockHeureka_DeleteIssueRepository_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteIssueRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteIssueRepository_Call) Return(_a0 error) *MockHeureka_DeleteIssueRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteIssueRepository_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteIssueRepository_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssueVariant provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteIssueVariant(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssueVariant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteIssueVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssueVariant'
type MockHeureka_DeleteIssueVariant_Call struct {
	*mock.Call
}

// DeleteIssueVariant is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteIssueVariant(_a0 interface{}) *MockHeureka_DeleteIssueVariant_Call {
	return &MockHeureka_DeleteIssueVariant_Call{Call: _e.mock.On("DeleteIssueVariant", _a0)}
}

func (_c *MockHeureka_DeleteIssueVariant_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteIssueVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteIssueVariant_Call) Return(_a0 error) *MockHeureka_DeleteIssueVariant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteIssueVariant_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteIssueVariant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteService provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteService(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteService'
type MockHeureka_DeleteService_Call struct {
	*mock.Call
}

// DeleteService is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteService(_a0 interface{}) *MockHeureka_DeleteService_Call {
	return &MockHeureka_DeleteService_Call{Call: _e.mock.On("DeleteService", _a0)}
}

func (_c *MockHeureka_DeleteService_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteService_Call) Return(_a0 error) *MockHeureka_DeleteService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteService_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteService_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSupportGroup provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteSupportGroup(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSupportGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteSupportGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSupportGroup'
type MockHeureka_DeleteSupportGroup_Call struct {
	*mock.Call
}

// DeleteSupportGroup is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteSupportGroup(_a0 interface{}) *MockHeureka_DeleteSupportGroup_Call {
	return &MockHeureka_DeleteSupportGroup_Call{Call: _e.mock.On("DeleteSupportGroup", _a0)}
}

func (_c *MockHeureka_DeleteSupportGroup_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteSupportGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteSupportGroup_Call) Return(_a0 error) *MockHeureka_DeleteSupportGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteSupportGroup_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteSupportGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: _a0
func (_m *MockHeureka) DeleteUser(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockHeureka_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockHeureka_Expecter) DeleteUser(_a0 interface{}) *MockHeureka_DeleteUser_Call {
	return &MockHeureka_DeleteUser_Call{Call: _e.mock.On("DeleteUser", _a0)}
}

func (_c *MockHeureka_DeleteUser_Call) Run(run func(_a0 int64)) *MockHeureka_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockHeureka_DeleteUser_Call) Return(_a0 error) *MockHeureka_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_DeleteUser_Call) RunAndReturn(run func(int64) error) *MockHeureka_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeverity provides a mock function with given fields: _a0
func (_m *MockHeureka) GetSeverity(_a0 *entity.SeverityFilter) (*entity.Severity, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetSeverity")
	}

	var r0 *entity.Severity
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.SeverityFilter) (*entity.Severity, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.SeverityFilter) *entity.Severity); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Severity)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.SeverityFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_GetSeverity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeverity'
type MockHeureka_GetSeverity_Call struct {
	*mock.Call
}

// GetSeverity is a helper method to define mock.On call
//   - _a0 *entity.SeverityFilter
func (_e *MockHeureka_Expecter) GetSeverity(_a0 interface{}) *MockHeureka_GetSeverity_Call {
	return &MockHeureka_GetSeverity_Call{Call: _e.mock.On("GetSeverity", _a0)}
}

func (_c *MockHeureka_GetSeverity_Call) Run(run func(_a0 *entity.SeverityFilter)) *MockHeureka_GetSeverity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.SeverityFilter))
	})
	return _c
}

func (_c *MockHeureka_GetSeverity_Call) Return(_a0 *entity.Severity, _a1 error) *MockHeureka_GetSeverity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_GetSeverity_Call) RunAndReturn(run func(*entity.SeverityFilter) (*entity.Severity, error)) *MockHeureka_GetSeverity_Call {
	_c.Call.Return(run)
	return _c
}

// ListActivities provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListActivities(_a0 *entity.ActivityFilter, _a1 *entity.ListOptions) (*entity.List[entity.ActivityResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListActivities")
	}

	var r0 *entity.List[entity.ActivityResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.ActivityFilter, *entity.ListOptions) (*entity.List[entity.ActivityResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.ActivityFilter, *entity.ListOptions) *entity.List[entity.ActivityResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.ActivityResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.ActivityFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActivities'
type MockHeureka_ListActivities_Call struct {
	*mock.Call
}

// ListActivities is a helper method to define mock.On call
//   - _a0 *entity.ActivityFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListActivities(_a0 interface{}, _a1 interface{}) *MockHeureka_ListActivities_Call {
	return &MockHeureka_ListActivities_Call{Call: _e.mock.On("ListActivities", _a0, _a1)}
}

func (_c *MockHeureka_ListActivities_Call) Run(run func(_a0 *entity.ActivityFilter, _a1 *entity.ListOptions)) *MockHeureka_ListActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.ActivityFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListActivities_Call) Return(_a0 *entity.List[entity.ActivityResult], _a1 error) *MockHeureka_ListActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListActivities_Call) RunAndReturn(run func(*entity.ActivityFilter, *entity.ListOptions) (*entity.List[entity.ActivityResult], error)) *MockHeureka_ListActivities_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponentInstances provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListComponentInstances(_a0 *entity.ComponentInstanceFilter, _a1 *entity.ListOptions) (*entity.List[entity.ComponentInstanceResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListComponentInstances")
	}

	var r0 *entity.List[entity.ComponentInstanceResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.ComponentInstanceFilter, *entity.ListOptions) (*entity.List[entity.ComponentInstanceResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.ComponentInstanceFilter, *entity.ListOptions) *entity.List[entity.ComponentInstanceResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.ComponentInstanceResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.ComponentInstanceFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListComponentInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponentInstances'
type MockHeureka_ListComponentInstances_Call struct {
	*mock.Call
}

// ListComponentInstances is a helper method to define mock.On call
//   - _a0 *entity.ComponentInstanceFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListComponentInstances(_a0 interface{}, _a1 interface{}) *MockHeureka_ListComponentInstances_Call {
	return &MockHeureka_ListComponentInstances_Call{Call: _e.mock.On("ListComponentInstances", _a0, _a1)}
}

func (_c *MockHeureka_ListComponentInstances_Call) Run(run func(_a0 *entity.ComponentInstanceFilter, _a1 *entity.ListOptions)) *MockHeureka_ListComponentInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.ComponentInstanceFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListComponentInstances_Call) Return(_a0 *entity.List[entity.ComponentInstanceResult], _a1 error) *MockHeureka_ListComponentInstances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListComponentInstances_Call) RunAndReturn(run func(*entity.ComponentInstanceFilter, *entity.ListOptions) (*entity.List[entity.ComponentInstanceResult], error)) *MockHeureka_ListComponentInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponentVersions provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListComponentVersions(_a0 *entity.ComponentVersionFilter, _a1 *entity.ListOptions) (*entity.List[entity.ComponentVersionResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListComponentVersions")
	}

	var r0 *entity.List[entity.ComponentVersionResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.ComponentVersionFilter, *entity.ListOptions) (*entity.List[entity.ComponentVersionResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.ComponentVersionFilter, *entity.ListOptions) *entity.List[entity.ComponentVersionResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.ComponentVersionResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.ComponentVersionFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListComponentVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponentVersions'
type MockHeureka_ListComponentVersions_Call struct {
	*mock.Call
}

// ListComponentVersions is a helper method to define mock.On call
//   - _a0 *entity.ComponentVersionFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListComponentVersions(_a0 interface{}, _a1 interface{}) *MockHeureka_ListComponentVersions_Call {
	return &MockHeureka_ListComponentVersions_Call{Call: _e.mock.On("ListComponentVersions", _a0, _a1)}
}

func (_c *MockHeureka_ListComponentVersions_Call) Run(run func(_a0 *entity.ComponentVersionFilter, _a1 *entity.ListOptions)) *MockHeureka_ListComponentVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.ComponentVersionFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListComponentVersions_Call) Return(_a0 *entity.List[entity.ComponentVersionResult], _a1 error) *MockHeureka_ListComponentVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListComponentVersions_Call) RunAndReturn(run func(*entity.ComponentVersionFilter, *entity.ListOptions) (*entity.List[entity.ComponentVersionResult], error)) *MockHeureka_ListComponentVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponents provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListComponents(_a0 *entity.ComponentFilter, _a1 *entity.ListOptions) (*entity.List[entity.ComponentResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListComponents")
	}

	var r0 *entity.List[entity.ComponentResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.ComponentFilter, *entity.ListOptions) (*entity.List[entity.ComponentResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.ComponentFilter, *entity.ListOptions) *entity.List[entity.ComponentResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.ComponentResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.ComponentFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponents'
type MockHeureka_ListComponents_Call struct {
	*mock.Call
}

// ListComponents is a helper method to define mock.On call
//   - _a0 *entity.ComponentFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListComponents(_a0 interface{}, _a1 interface{}) *MockHeureka_ListComponents_Call {
	return &MockHeureka_ListComponents_Call{Call: _e.mock.On("ListComponents", _a0, _a1)}
}

func (_c *MockHeureka_ListComponents_Call) Run(run func(_a0 *entity.ComponentFilter, _a1 *entity.ListOptions)) *MockHeureka_ListComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.ComponentFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListComponents_Call) Return(_a0 *entity.List[entity.ComponentResult], _a1 error) *MockHeureka_ListComponents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListComponents_Call) RunAndReturn(run func(*entity.ComponentFilter, *entity.ListOptions) (*entity.List[entity.ComponentResult], error)) *MockHeureka_ListComponents_Call {
	_c.Call.Return(run)
	return _c
}

// ListEffectiveIssueVariants provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListEffectiveIssueVariants(_a0 *entity.IssueVariantFilter, _a1 *entity.ListOptions) (*entity.List[entity.IssueVariantResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListEffectiveIssueVariants")
	}

	var r0 *entity.List[entity.IssueVariantResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueVariantFilter, *entity.ListOptions) (*entity.List[entity.IssueVariantResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueVariantFilter, *entity.ListOptions) *entity.List[entity.IssueVariantResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.IssueVariantResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueVariantFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListEffectiveIssueVariants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEffectiveIssueVariants'
type MockHeureka_ListEffectiveIssueVariants_Call struct {
	*mock.Call
}

// ListEffectiveIssueVariants is a helper method to define mock.On call
//   - _a0 *entity.IssueVariantFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListEffectiveIssueVariants(_a0 interface{}, _a1 interface{}) *MockHeureka_ListEffectiveIssueVariants_Call {
	return &MockHeureka_ListEffectiveIssueVariants_Call{Call: _e.mock.On("ListEffectiveIssueVariants", _a0, _a1)}
}

func (_c *MockHeureka_ListEffectiveIssueVariants_Call) Run(run func(_a0 *entity.IssueVariantFilter, _a1 *entity.ListOptions)) *MockHeureka_ListEffectiveIssueVariants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueVariantFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListEffectiveIssueVariants_Call) Return(_a0 *entity.List[entity.IssueVariantResult], _a1 error) *MockHeureka_ListEffectiveIssueVariants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListEffectiveIssueVariants_Call) RunAndReturn(run func(*entity.IssueVariantFilter, *entity.ListOptions) (*entity.List[entity.IssueVariantResult], error)) *MockHeureka_ListEffectiveIssueVariants_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvidences provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListEvidences(_a0 *entity.EvidenceFilter, _a1 *entity.ListOptions) (*entity.List[entity.EvidenceResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListEvidences")
	}

	var r0 *entity.List[entity.EvidenceResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.EvidenceFilter, *entity.ListOptions) (*entity.List[entity.EvidenceResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.EvidenceFilter, *entity.ListOptions) *entity.List[entity.EvidenceResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.EvidenceResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.EvidenceFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListEvidences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvidences'
type MockHeureka_ListEvidences_Call struct {
	*mock.Call
}

// ListEvidences is a helper method to define mock.On call
//   - _a0 *entity.EvidenceFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListEvidences(_a0 interface{}, _a1 interface{}) *MockHeureka_ListEvidences_Call {
	return &MockHeureka_ListEvidences_Call{Call: _e.mock.On("ListEvidences", _a0, _a1)}
}

func (_c *MockHeureka_ListEvidences_Call) Run(run func(_a0 *entity.EvidenceFilter, _a1 *entity.ListOptions)) *MockHeureka_ListEvidences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.EvidenceFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListEvidences_Call) Return(_a0 *entity.List[entity.EvidenceResult], _a1 error) *MockHeureka_ListEvidences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListEvidences_Call) RunAndReturn(run func(*entity.EvidenceFilter, *entity.ListOptions) (*entity.List[entity.EvidenceResult], error)) *MockHeureka_ListEvidences_Call {
	_c.Call.Return(run)
	return _c
}

// ListIssueMatchChanges provides a mock function with given fields: filter, options
func (_m *MockHeureka) ListIssueMatchChanges(filter *entity.IssueMatchChangeFilter, options *entity.ListOptions) (*entity.List[entity.IssueMatchChangeResult], error) {
	ret := _m.Called(filter, options)

	if len(ret) == 0 {
		panic("no return value specified for ListIssueMatchChanges")
	}

	var r0 *entity.List[entity.IssueMatchChangeResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueMatchChangeFilter, *entity.ListOptions) (*entity.List[entity.IssueMatchChangeResult], error)); ok {
		return rf(filter, options)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueMatchChangeFilter, *entity.ListOptions) *entity.List[entity.IssueMatchChangeResult]); ok {
		r0 = rf(filter, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.IssueMatchChangeResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueMatchChangeFilter, *entity.ListOptions) error); ok {
		r1 = rf(filter, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListIssueMatchChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIssueMatchChanges'
type MockHeureka_ListIssueMatchChanges_Call struct {
	*mock.Call
}

// ListIssueMatchChanges is a helper method to define mock.On call
//   - filter *entity.IssueMatchChangeFilter
//   - options *entity.ListOptions
func (_e *MockHeureka_Expecter) ListIssueMatchChanges(filter interface{}, options interface{}) *MockHeureka_ListIssueMatchChanges_Call {
	return &MockHeureka_ListIssueMatchChanges_Call{Call: _e.mock.On("ListIssueMatchChanges", filter, options)}
}

func (_c *MockHeureka_ListIssueMatchChanges_Call) Run(run func(filter *entity.IssueMatchChangeFilter, options *entity.ListOptions)) *MockHeureka_ListIssueMatchChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueMatchChangeFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListIssueMatchChanges_Call) Return(_a0 *entity.List[entity.IssueMatchChangeResult], _a1 error) *MockHeureka_ListIssueMatchChanges_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListIssueMatchChanges_Call) RunAndReturn(run func(*entity.IssueMatchChangeFilter, *entity.ListOptions) (*entity.List[entity.IssueMatchChangeResult], error)) *MockHeureka_ListIssueMatchChanges_Call {
	_c.Call.Return(run)
	return _c
}

// ListIssueMatches provides a mock function with given fields: filter, options
func (_m *MockHeureka) ListIssueMatches(filter *entity.IssueMatchFilter, options *entity.ListOptions) (*entity.List[entity.IssueMatchResult], error) {
	ret := _m.Called(filter, options)

	if len(ret) == 0 {
		panic("no return value specified for ListIssueMatches")
	}

	var r0 *entity.List[entity.IssueMatchResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueMatchFilter, *entity.ListOptions) (*entity.List[entity.IssueMatchResult], error)); ok {
		return rf(filter, options)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueMatchFilter, *entity.ListOptions) *entity.List[entity.IssueMatchResult]); ok {
		r0 = rf(filter, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.IssueMatchResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueMatchFilter, *entity.ListOptions) error); ok {
		r1 = rf(filter, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListIssueMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIssueMatches'
type MockHeureka_ListIssueMatches_Call struct {
	*mock.Call
}

// ListIssueMatches is a helper method to define mock.On call
//   - filter *entity.IssueMatchFilter
//   - options *entity.ListOptions
func (_e *MockHeureka_Expecter) ListIssueMatches(filter interface{}, options interface{}) *MockHeureka_ListIssueMatches_Call {
	return &MockHeureka_ListIssueMatches_Call{Call: _e.mock.On("ListIssueMatches", filter, options)}
}

func (_c *MockHeureka_ListIssueMatches_Call) Run(run func(filter *entity.IssueMatchFilter, options *entity.ListOptions)) *MockHeureka_ListIssueMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueMatchFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListIssueMatches_Call) Return(_a0 *entity.List[entity.IssueMatchResult], _a1 error) *MockHeureka_ListIssueMatches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListIssueMatches_Call) RunAndReturn(run func(*entity.IssueMatchFilter, *entity.ListOptions) (*entity.List[entity.IssueMatchResult], error)) *MockHeureka_ListIssueMatches_Call {
	_c.Call.Return(run)
	return _c
}

// ListIssueRepositories provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListIssueRepositories(_a0 *entity.IssueRepositoryFilter, _a1 *entity.ListOptions) (*entity.List[entity.IssueRepositoryResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListIssueRepositories")
	}

	var r0 *entity.List[entity.IssueRepositoryResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueRepositoryFilter, *entity.ListOptions) (*entity.List[entity.IssueRepositoryResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueRepositoryFilter, *entity.ListOptions) *entity.List[entity.IssueRepositoryResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.IssueRepositoryResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueRepositoryFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListIssueRepositories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIssueRepositories'
type MockHeureka_ListIssueRepositories_Call struct {
	*mock.Call
}

// ListIssueRepositories is a helper method to define mock.On call
//   - _a0 *entity.IssueRepositoryFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListIssueRepositories(_a0 interface{}, _a1 interface{}) *MockHeureka_ListIssueRepositories_Call {
	return &MockHeureka_ListIssueRepositories_Call{Call: _e.mock.On("ListIssueRepositories", _a0, _a1)}
}

func (_c *MockHeureka_ListIssueRepositories_Call) Run(run func(_a0 *entity.IssueRepositoryFilter, _a1 *entity.ListOptions)) *MockHeureka_ListIssueRepositories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueRepositoryFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListIssueRepositories_Call) Return(_a0 *entity.List[entity.IssueRepositoryResult], _a1 error) *MockHeureka_ListIssueRepositories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListIssueRepositories_Call) RunAndReturn(run func(*entity.IssueRepositoryFilter, *entity.ListOptions) (*entity.List[entity.IssueRepositoryResult], error)) *MockHeureka_ListIssueRepositories_Call {
	_c.Call.Return(run)
	return _c
}

// ListIssueVariants provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListIssueVariants(_a0 *entity.IssueVariantFilter, _a1 *entity.ListOptions) (*entity.List[entity.IssueVariantResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListIssueVariants")
	}

	var r0 *entity.List[entity.IssueVariantResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueVariantFilter, *entity.ListOptions) (*entity.List[entity.IssueVariantResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueVariantFilter, *entity.ListOptions) *entity.List[entity.IssueVariantResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.IssueVariantResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueVariantFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListIssueVariants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIssueVariants'
type MockHeureka_ListIssueVariants_Call struct {
	*mock.Call
}

// ListIssueVariants is a helper method to define mock.On call
//   - _a0 *entity.IssueVariantFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListIssueVariants(_a0 interface{}, _a1 interface{}) *MockHeureka_ListIssueVariants_Call {
	return &MockHeureka_ListIssueVariants_Call{Call: _e.mock.On("ListIssueVariants", _a0, _a1)}
}

func (_c *MockHeureka_ListIssueVariants_Call) Run(run func(_a0 *entity.IssueVariantFilter, _a1 *entity.ListOptions)) *MockHeureka_ListIssueVariants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueVariantFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListIssueVariants_Call) Return(_a0 *entity.List[entity.IssueVariantResult], _a1 error) *MockHeureka_ListIssueVariants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListIssueVariants_Call) RunAndReturn(run func(*entity.IssueVariantFilter, *entity.ListOptions) (*entity.List[entity.IssueVariantResult], error)) *MockHeureka_ListIssueVariants_Call {
	_c.Call.Return(run)
	return _c
}

// ListIssues provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListIssues(_a0 *entity.IssueFilter, _a1 *entity.ListOptions) (*entity.List[entity.IssueResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListIssues")
	}

	var r0 *entity.List[entity.IssueResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueFilter, *entity.ListOptions) (*entity.List[entity.IssueResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueFilter, *entity.ListOptions) *entity.List[entity.IssueResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.IssueResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListIssues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIssues'
type MockHeureka_ListIssues_Call struct {
	*mock.Call
}

// ListIssues is a helper method to define mock.On call
//   - _a0 *entity.IssueFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListIssues(_a0 interface{}, _a1 interface{}) *MockHeureka_ListIssues_Call {
	return &MockHeureka_ListIssues_Call{Call: _e.mock.On("ListIssues", _a0, _a1)}
}

func (_c *MockHeureka_ListIssues_Call) Run(run func(_a0 *entity.IssueFilter, _a1 *entity.ListOptions)) *MockHeureka_ListIssues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListIssues_Call) Return(_a0 *entity.List[entity.IssueResult], _a1 error) *MockHeureka_ListIssues_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListIssues_Call) RunAndReturn(run func(*entity.IssueFilter, *entity.ListOptions) (*entity.List[entity.IssueResult], error)) *MockHeureka_ListIssues_Call {
	_c.Call.Return(run)
	return _c
}

// ListServices provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListServices(_a0 *entity.ServiceFilter, _a1 *entity.ListOptions) (*entity.List[entity.ServiceResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 *entity.List[entity.ServiceResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.ServiceFilter, *entity.ListOptions) (*entity.List[entity.ServiceResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.ServiceFilter, *entity.ListOptions) *entity.List[entity.ServiceResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.ServiceResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.ServiceFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServices'
type MockHeureka_ListServices_Call struct {
	*mock.Call
}

// ListServices is a helper method to define mock.On call
//   - _a0 *entity.ServiceFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListServices(_a0 interface{}, _a1 interface{}) *MockHeureka_ListServices_Call {
	return &MockHeureka_ListServices_Call{Call: _e.mock.On("ListServices", _a0, _a1)}
}

func (_c *MockHeureka_ListServices_Call) Run(run func(_a0 *entity.ServiceFilter, _a1 *entity.ListOptions)) *MockHeureka_ListServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.ServiceFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListServices_Call) Return(_a0 *entity.List[entity.ServiceResult], _a1 error) *MockHeureka_ListServices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListServices_Call) RunAndReturn(run func(*entity.ServiceFilter, *entity.ListOptions) (*entity.List[entity.ServiceResult], error)) *MockHeureka_ListServices_Call {
	_c.Call.Return(run)
	return _c
}

// ListSupportGroups provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListSupportGroups(_a0 *entity.SupportGroupFilter, _a1 *entity.ListOptions) (*entity.List[entity.SupportGroupResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListSupportGroups")
	}

	var r0 *entity.List[entity.SupportGroupResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.SupportGroupFilter, *entity.ListOptions) (*entity.List[entity.SupportGroupResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.SupportGroupFilter, *entity.ListOptions) *entity.List[entity.SupportGroupResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.SupportGroupResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.SupportGroupFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListSupportGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSupportGroups'
type MockHeureka_ListSupportGroups_Call struct {
	*mock.Call
}

// ListSupportGroups is a helper method to define mock.On call
//   - _a0 *entity.SupportGroupFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListSupportGroups(_a0 interface{}, _a1 interface{}) *MockHeureka_ListSupportGroups_Call {
	return &MockHeureka_ListSupportGroups_Call{Call: _e.mock.On("ListSupportGroups", _a0, _a1)}
}

func (_c *MockHeureka_ListSupportGroups_Call) Run(run func(_a0 *entity.SupportGroupFilter, _a1 *entity.ListOptions)) *MockHeureka_ListSupportGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.SupportGroupFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListSupportGroups_Call) Return(_a0 *entity.List[entity.SupportGroupResult], _a1 error) *MockHeureka_ListSupportGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListSupportGroups_Call) RunAndReturn(run func(*entity.SupportGroupFilter, *entity.ListOptions) (*entity.List[entity.SupportGroupResult], error)) *MockHeureka_ListSupportGroups_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: _a0, _a1
func (_m *MockHeureka) ListUsers(_a0 *entity.UserFilter, _a1 *entity.ListOptions) (*entity.List[entity.UserResult], error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *entity.List[entity.UserResult]
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.UserFilter, *entity.ListOptions) (*entity.List[entity.UserResult], error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*entity.UserFilter, *entity.ListOptions) *entity.List[entity.UserResult]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.List[entity.UserResult])
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.UserFilter, *entity.ListOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockHeureka_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - _a0 *entity.UserFilter
//   - _a1 *entity.ListOptions
func (_e *MockHeureka_Expecter) ListUsers(_a0 interface{}, _a1 interface{}) *MockHeureka_ListUsers_Call {
	return &MockHeureka_ListUsers_Call{Call: _e.mock.On("ListUsers", _a0, _a1)}
}

func (_c *MockHeureka_ListUsers_Call) Run(run func(_a0 *entity.UserFilter, _a1 *entity.ListOptions)) *MockHeureka_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.UserFilter), args[1].(*entity.ListOptions))
	})
	return _c
}

func (_c *MockHeureka_ListUsers_Call) Return(_a0 *entity.List[entity.UserResult], _a1 error) *MockHeureka_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_ListUsers_Call) RunAndReturn(run func(*entity.UserFilter, *entity.ListOptions) (*entity.List[entity.UserResult], error)) *MockHeureka_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields:
func (_m *MockHeureka) Shutdown() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeureka_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockHeureka_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockHeureka_Expecter) Shutdown() *MockHeureka_Shutdown_Call {
	return &MockHeureka_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockHeureka_Shutdown_Call) Run(run func()) *MockHeureka_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHeureka_Shutdown_Call) Return(_a0 error) *MockHeureka_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeureka_Shutdown_Call) RunAndReturn(run func() error) *MockHeureka_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActivity provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateActivity(_a0 *entity.Activity) (*entity.Activity, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActivity")
	}

	var r0 *entity.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Activity) (*entity.Activity, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Activity) *entity.Activity); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Activity) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActivity'
type MockHeureka_UpdateActivity_Call struct {
	*mock.Call
}

// UpdateActivity is a helper method to define mock.On call
//   - _a0 *entity.Activity
func (_e *MockHeureka_Expecter) UpdateActivity(_a0 interface{}) *MockHeureka_UpdateActivity_Call {
	return &MockHeureka_UpdateActivity_Call{Call: _e.mock.On("UpdateActivity", _a0)}
}

func (_c *MockHeureka_UpdateActivity_Call) Run(run func(_a0 *entity.Activity)) *MockHeureka_UpdateActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Activity))
	})
	return _c
}

func (_c *MockHeureka_UpdateActivity_Call) Return(_a0 *entity.Activity, _a1 error) *MockHeureka_UpdateActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateActivity_Call) RunAndReturn(run func(*entity.Activity) (*entity.Activity, error)) *MockHeureka_UpdateActivity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComponent provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateComponent(_a0 *entity.Component) (*entity.Component, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComponent")
	}

	var r0 *entity.Component
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Component) (*entity.Component, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Component) *entity.Component); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Component)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Component) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponent'
type MockHeureka_UpdateComponent_Call struct {
	*mock.Call
}

// UpdateComponent is a helper method to define mock.On call
//   - _a0 *entity.Component
func (_e *MockHeureka_Expecter) UpdateComponent(_a0 interface{}) *MockHeureka_UpdateComponent_Call {
	return &MockHeureka_UpdateComponent_Call{Call: _e.mock.On("UpdateComponent", _a0)}
}

func (_c *MockHeureka_UpdateComponent_Call) Run(run func(_a0 *entity.Component)) *MockHeureka_UpdateComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Component))
	})
	return _c
}

func (_c *MockHeureka_UpdateComponent_Call) Return(_a0 *entity.Component, _a1 error) *MockHeureka_UpdateComponent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateComponent_Call) RunAndReturn(run func(*entity.Component) (*entity.Component, error)) *MockHeureka_UpdateComponent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComponentInstance provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateComponentInstance(_a0 *entity.ComponentInstance) (*entity.ComponentInstance, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComponentInstance")
	}

	var r0 *entity.ComponentInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.ComponentInstance) (*entity.ComponentInstance, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.ComponentInstance) *entity.ComponentInstance); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ComponentInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.ComponentInstance) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateComponentInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponentInstance'
type MockHeureka_UpdateComponentInstance_Call struct {
	*mock.Call
}

// UpdateComponentInstance is a helper method to define mock.On call
//   - _a0 *entity.ComponentInstance
func (_e *MockHeureka_Expecter) UpdateComponentInstance(_a0 interface{}) *MockHeureka_UpdateComponentInstance_Call {
	return &MockHeureka_UpdateComponentInstance_Call{Call: _e.mock.On("UpdateComponentInstance", _a0)}
}

func (_c *MockHeureka_UpdateComponentInstance_Call) Run(run func(_a0 *entity.ComponentInstance)) *MockHeureka_UpdateComponentInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.ComponentInstance))
	})
	return _c
}

func (_c *MockHeureka_UpdateComponentInstance_Call) Return(_a0 *entity.ComponentInstance, _a1 error) *MockHeureka_UpdateComponentInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateComponentInstance_Call) RunAndReturn(run func(*entity.ComponentInstance) (*entity.ComponentInstance, error)) *MockHeureka_UpdateComponentInstance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComponentVersion provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateComponentVersion(_a0 *entity.ComponentVersion) (*entity.ComponentVersion, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComponentVersion")
	}

	var r0 *entity.ComponentVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.ComponentVersion) (*entity.ComponentVersion, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.ComponentVersion) *entity.ComponentVersion); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ComponentVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.ComponentVersion) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateComponentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponentVersion'
type MockHeureka_UpdateComponentVersion_Call struct {
	*mock.Call
}

// UpdateComponentVersion is a helper method to define mock.On call
//   - _a0 *entity.ComponentVersion
func (_e *MockHeureka_Expecter) UpdateComponentVersion(_a0 interface{}) *MockHeureka_UpdateComponentVersion_Call {
	return &MockHeureka_UpdateComponentVersion_Call{Call: _e.mock.On("UpdateComponentVersion", _a0)}
}

func (_c *MockHeureka_UpdateComponentVersion_Call) Run(run func(_a0 *entity.ComponentVersion)) *MockHeureka_UpdateComponentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.ComponentVersion))
	})
	return _c
}

func (_c *MockHeureka_UpdateComponentVersion_Call) Return(_a0 *entity.ComponentVersion, _a1 error) *MockHeureka_UpdateComponentVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateComponentVersion_Call) RunAndReturn(run func(*entity.ComponentVersion) (*entity.ComponentVersion, error)) *MockHeureka_UpdateComponentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvidence provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateEvidence(_a0 *entity.Evidence) (*entity.Evidence, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvidence")
	}

	var r0 *entity.Evidence
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Evidence) (*entity.Evidence, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Evidence) *entity.Evidence); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Evidence)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Evidence) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvidence'
type MockHeureka_UpdateEvidence_Call struct {
	*mock.Call
}

// UpdateEvidence is a helper method to define mock.On call
//   - _a0 *entity.Evidence
func (_e *MockHeureka_Expecter) UpdateEvidence(_a0 interface{}) *MockHeureka_UpdateEvidence_Call {
	return &MockHeureka_UpdateEvidence_Call{Call: _e.mock.On("UpdateEvidence", _a0)}
}

func (_c *MockHeureka_UpdateEvidence_Call) Run(run func(_a0 *entity.Evidence)) *MockHeureka_UpdateEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Evidence))
	})
	return _c
}

func (_c *MockHeureka_UpdateEvidence_Call) Return(_a0 *entity.Evidence, _a1 error) *MockHeureka_UpdateEvidence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateEvidence_Call) RunAndReturn(run func(*entity.Evidence) (*entity.Evidence, error)) *MockHeureka_UpdateEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIssue provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateIssue(_a0 *entity.Issue) (*entity.Issue, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIssue")
	}

	var r0 *entity.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Issue) (*entity.Issue, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Issue) *entity.Issue); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Issue) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIssue'
type MockHeureka_UpdateIssue_Call struct {
	*mock.Call
}

// UpdateIssue is a helper method to define mock.On call
//   - _a0 *entity.Issue
func (_e *MockHeureka_Expecter) UpdateIssue(_a0 interface{}) *MockHeureka_UpdateIssue_Call {
	return &MockHeureka_UpdateIssue_Call{Call: _e.mock.On("UpdateIssue", _a0)}
}

func (_c *MockHeureka_UpdateIssue_Call) Run(run func(_a0 *entity.Issue)) *MockHeureka_UpdateIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Issue))
	})
	return _c
}

func (_c *MockHeureka_UpdateIssue_Call) Return(_a0 *entity.Issue, _a1 error) *MockHeureka_UpdateIssue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateIssue_Call) RunAndReturn(run func(*entity.Issue) (*entity.Issue, error)) *MockHeureka_UpdateIssue_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIssueMatch provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateIssueMatch(_a0 *entity.IssueMatch) (*entity.IssueMatch, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIssueMatch")
	}

	var r0 *entity.IssueMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueMatch) (*entity.IssueMatch, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueMatch) *entity.IssueMatch); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.IssueMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueMatch) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateIssueMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIssueMatch'
type MockHeureka_UpdateIssueMatch_Call struct {
	*mock.Call
}

// UpdateIssueMatch is a helper method to define mock.On call
//   - _a0 *entity.IssueMatch
func (_e *MockHeureka_Expecter) UpdateIssueMatch(_a0 interface{}) *MockHeureka_UpdateIssueMatch_Call {
	return &MockHeureka_UpdateIssueMatch_Call{Call: _e.mock.On("UpdateIssueMatch", _a0)}
}

func (_c *MockHeureka_UpdateIssueMatch_Call) Run(run func(_a0 *entity.IssueMatch)) *MockHeureka_UpdateIssueMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueMatch))
	})
	return _c
}

func (_c *MockHeureka_UpdateIssueMatch_Call) Return(_a0 *entity.IssueMatch, _a1 error) *MockHeureka_UpdateIssueMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateIssueMatch_Call) RunAndReturn(run func(*entity.IssueMatch) (*entity.IssueMatch, error)) *MockHeureka_UpdateIssueMatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIssueRepository provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateIssueRepository(_a0 *entity.IssueRepository) (*entity.IssueRepository, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIssueRepository")
	}

	var r0 *entity.IssueRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueRepository) (*entity.IssueRepository, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueRepository) *entity.IssueRepository); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.IssueRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueRepository) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateIssueRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIssueRepository'
type MockHeureka_UpdateIssueRepository_Call struct {
	*mock.Call
}

// UpdateIssueRepository is a helper method to define mock.On call
//   - _a0 *entity.IssueRepository
func (_e *MockHeureka_Expecter) UpdateIssueRepository(_a0 interface{}) *MockHeureka_UpdateIssueRepository_Call {
	return &MockHeureka_UpdateIssueRepository_Call{Call: _e.mock.On("UpdateIssueRepository", _a0)}
}

func (_c *MockHeureka_UpdateIssueRepository_Call) Run(run func(_a0 *entity.IssueRepository)) *MockHeureka_UpdateIssueRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueRepository))
	})
	return _c
}

func (_c *MockHeureka_UpdateIssueRepository_Call) Return(_a0 *entity.IssueRepository, _a1 error) *MockHeureka_UpdateIssueRepository_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateIssueRepository_Call) RunAndReturn(run func(*entity.IssueRepository) (*entity.IssueRepository, error)) *MockHeureka_UpdateIssueRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIssueVariant provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateIssueVariant(_a0 *entity.IssueVariant) (*entity.IssueVariant, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIssueVariant")
	}

	var r0 *entity.IssueVariant
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.IssueVariant) (*entity.IssueVariant, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.IssueVariant) *entity.IssueVariant); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.IssueVariant)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.IssueVariant) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateIssueVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIssueVariant'
type MockHeureka_UpdateIssueVariant_Call struct {
	*mock.Call
}

// UpdateIssueVariant is a helper method to define mock.On call
//   - _a0 *entity.IssueVariant
func (_e *MockHeureka_Expecter) UpdateIssueVariant(_a0 interface{}) *MockHeureka_UpdateIssueVariant_Call {
	return &MockHeureka_UpdateIssueVariant_Call{Call: _e.mock.On("UpdateIssueVariant", _a0)}
}

func (_c *MockHeureka_UpdateIssueVariant_Call) Run(run func(_a0 *entity.IssueVariant)) *MockHeureka_UpdateIssueVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.IssueVariant))
	})
	return _c
}

func (_c *MockHeureka_UpdateIssueVariant_Call) Return(_a0 *entity.IssueVariant, _a1 error) *MockHeureka_UpdateIssueVariant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateIssueVariant_Call) RunAndReturn(run func(*entity.IssueVariant) (*entity.IssueVariant, error)) *MockHeureka_UpdateIssueVariant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateService provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateService(_a0 *entity.Service) (*entity.Service, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateService")
	}

	var r0 *entity.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Service) (*entity.Service, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Service) *entity.Service); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Service) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateService'
type MockHeureka_UpdateService_Call struct {
	*mock.Call
}

// UpdateService is a helper method to define mock.On call
//   - _a0 *entity.Service
func (_e *MockHeureka_Expecter) UpdateService(_a0 interface{}) *MockHeureka_UpdateService_Call {
	return &MockHeureka_UpdateService_Call{Call: _e.mock.On("UpdateService", _a0)}
}

func (_c *MockHeureka_UpdateService_Call) Run(run func(_a0 *entity.Service)) *MockHeureka_UpdateService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Service))
	})
	return _c
}

func (_c *MockHeureka_UpdateService_Call) Return(_a0 *entity.Service, _a1 error) *MockHeureka_UpdateService_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateService_Call) RunAndReturn(run func(*entity.Service) (*entity.Service, error)) *MockHeureka_UpdateService_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSupportGroup provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateSupportGroup(_a0 *entity.SupportGroup) (*entity.SupportGroup, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSupportGroup")
	}

	var r0 *entity.SupportGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.SupportGroup) (*entity.SupportGroup, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.SupportGroup) *entity.SupportGroup); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SupportGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.SupportGroup) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateSupportGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSupportGroup'
type MockHeureka_UpdateSupportGroup_Call struct {
	*mock.Call
}

// UpdateSupportGroup is a helper method to define mock.On call
//   - _a0 *entity.SupportGroup
func (_e *MockHeureka_Expecter) UpdateSupportGroup(_a0 interface{}) *MockHeureka_UpdateSupportGroup_Call {
	return &MockHeureka_UpdateSupportGroup_Call{Call: _e.mock.On("UpdateSupportGroup", _a0)}
}

func (_c *MockHeureka_UpdateSupportGroup_Call) Run(run func(_a0 *entity.SupportGroup)) *MockHeureka_UpdateSupportGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.SupportGroup))
	})
	return _c
}

func (_c *MockHeureka_UpdateSupportGroup_Call) Return(_a0 *entity.SupportGroup, _a1 error) *MockHeureka_UpdateSupportGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateSupportGroup_Call) RunAndReturn(run func(*entity.SupportGroup) (*entity.SupportGroup, error)) *MockHeureka_UpdateSupportGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: _a0
func (_m *MockHeureka) UpdateUser(_a0 *entity.User) (*entity.User, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.User) (*entity.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.User) *entity.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeureka_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockHeureka_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - _a0 *entity.User
func (_e *MockHeureka_Expecter) UpdateUser(_a0 interface{}) *MockHeureka_UpdateUser_Call {
	return &MockHeureka_UpdateUser_Call{Call: _e.mock.On("UpdateUser", _a0)}
}

func (_c *MockHeureka_UpdateUser_Call) Run(run func(_a0 *entity.User)) *MockHeureka_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.User))
	})
	return _c
}

func (_c *MockHeureka_UpdateUser_Call) Return(_a0 *entity.User, _a1 error) *MockHeureka_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeureka_UpdateUser_Call) RunAndReturn(run func(*entity.User) (*entity.User, error)) *MockHeureka_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHeureka creates a new instance of MockHeureka. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeureka(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeureka {
	mock := &MockHeureka{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
