package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.wdf.sap.corp/cc/heureka/internal/api/graphql/graph"
	"github.wdf.sap.corp/cc/heureka/internal/api/graphql/graph/baseResolver"
	"github.wdf.sap.corp/cc/heureka/internal/api/graphql/graph/model"
)

// ComponentVersions is the resolver for the componentVersions field.
func (r *componentResolver) ComponentVersions(ctx context.Context, obj *model.Component, filter *model.ComponentVersionFilter, first *int, after *string) (*model.ComponentVersionConnection, error) {
	return baseResolver.ComponentVersionBaseResolver(r.App, ctx, filter, first, after,
		&model.NodeParent{
			Parent:     obj,
			ParentName: model.ComponentNodeName,
		})
}

// Component returns graph.ComponentResolver implementation.
func (r *Resolver) Component() graph.ComponentResolver { return &componentResolver{r} }

type componentResolver struct{ *Resolver }
