package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/cloudoperators/heureka/internal/api/graphql/graph"
	"github.com/cloudoperators/heureka/internal/api/graphql/graph/baseResolver"
	"github.com/cloudoperators/heureka/internal/api/graphql/graph/model"
)

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
// SPDX-License-Identifier: Apache-2.0

func (r *imageVersionResolver) Occurences(ctx context.Context, obj *model.ImageVersion, first *int, after *string) (*model.ComponentInstanceConnection, error) {
	rootCtx := baseResolver.GetRoot(graphql.GetFieldContext(ctx))
	ivFilter := rootCtx.Args["filter"].(*model.ImageVersionFilter)
	if ivFilter == nil {
		ivFilter = &model.ImageVersionFilter{}
	}
	filter := &model.ComponentInstanceFilter{
		ServiceCcrn:            ivFilter.Service,
		ComponentVersionDigest: ivFilter.Version,
	}
	return baseResolver.ComponentInstanceBaseResolver(r.App, ctx, filter, first, after, nil, &model.NodeParent{
		Parent:     obj,
		ParentName: model.ComponentVersionNodeName,
	})
}

func (r *imageVersionResolver) Vulnerabilities(ctx context.Context, obj *model.ImageVersion, first *int, after *string, filter *model.VulnerabilityFilter) (*model.VulnerabilityConnection, error) {
	rootCtx := baseResolver.GetRoot(graphql.GetFieldContext(ctx))
	ivFilter := rootCtx.Args["filter"].(*model.ImageVersionFilter)

	if ivFilter == nil {
		ivFilter = &model.ImageVersionFilter{}
	}

	if filter == nil {
		filter = &model.VulnerabilityFilter{}
	}

	filter.Service = append(filter.Service, ivFilter.Service...)

	return baseResolver.VulnerabilityBaseResolver(r.App, ctx, filter, first, after, &model.NodeParent{
		Parent:     obj,
		ParentName: model.ImageVersionNodeName,
	})
}

func (r *imageVersionResolver) VulnerabilityCounts(ctx context.Context, obj *model.ImageVersion) (*model.SeverityCounts, error) {
	rootCtx := baseResolver.GetRoot(graphql.GetFieldContext(ctx))
	ivFilter := rootCtx.Args["filter"].(*model.ImageVersionFilter)
	if ivFilter == nil {
		ivFilter = &model.ImageVersionFilter{}
	}
	filter := &model.IssueFilter{
		ServiceCcrn:        ivFilter.Service,
		ComponentVersionID: []*string{&obj.ID},
	}
	return baseResolver.IssueCountsBaseResolver(r.App, ctx, filter, &model.NodeParent{
		Parent:     obj,
		ParentName: model.ImageVersionNodeName,
	})
}

func (r *Resolver) ImageVersion() graph.ImageVersionResolver { return &imageVersionResolver{r} }

type imageVersionResolver struct{ *Resolver }
