package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/cloudoperators/heureka/internal/api/graphql/dataloader"
	"github.com/cloudoperators/heureka/internal/api/graphql/graph"
	"github.com/cloudoperators/heureka/internal/api/graphql/graph/baseResolver"
	"github.com/cloudoperators/heureka/internal/api/graphql/graph/model"
	"github.com/cloudoperators/heureka/internal/entity"
)

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
// SPDX-License-Identifier: Apache-2.0

func (r *issueMatchResolver) EffectiveIssueVariants(ctx context.Context, obj *model.IssueMatch, filter *model.IssueVariantFilter, first *int, after *string) (*model.IssueVariantConnection, error) {
	return baseResolver.EffectiveIssueVariantBaseResolver(
		r.App,
		ctx,
		filter,
		first,
		after,
		&model.NodeParent{
			Parent:     obj,
			ParentName: model.IssueMatchNodeName,
		},
	)
}

func (r *issueMatchResolver) Issue(ctx context.Context, obj *model.IssueMatch) (*model.Issue, error) {
	id, err := baseResolver.ParseCursor(obj.IssueID)
	if err != nil {
		return nil, err
	}

	iss, err := dataloader.FromContext(ctx).IssueByID.Load(ctx, *id)
	if err != nil || iss == nil {
		return nil, err
	}

	result := model.NewIssueWithAggregations(&entity.IssueResult{Issue: iss})

	return &result, nil
}

func (r *issueMatchResolver) ComponentInstance(ctx context.Context, obj *model.IssueMatch) (*model.ComponentInstance, error) {
	id, err := baseResolver.ParseCursor(obj.ComponentInstanceID)
	if err != nil {
		return nil, err
	}

	ci, err := dataloader.FromContext(ctx).ComponentInstanceByID.Load(ctx, *id)
	if err != nil || ci == nil {
		return nil, err
	}

	result := model.NewComponentInstance(ci)

	return &result, nil
}

func (r *Resolver) IssueMatch() graph.IssueMatchResolver { return &issueMatchResolver{r} }

type issueMatchResolver struct{ *Resolver }
