package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/cloudoperators/heureka/internal/api/graphql/graph"
	"github.com/cloudoperators/heureka/internal/api/graphql/graph/baseResolver"
	"github.com/cloudoperators/heureka/internal/api/graphql/graph/model"
)

// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
// SPDX-License-Identifier: Apache-2.0

func (r *sIEMAlertNodeResolver) Comments(ctx context.Context, obj *model.SIEMAlertNode, filter *model.SIEMAlertCommentFilter, first *int, after *string) (*model.SIEMAlertCommentConnection, error) {
	return baseResolver.SIEMAlertCommentBaseResolver(
		r.App,
		ctx,
		filter,
		first,
		after,
		&model.NodeParent{
			Parent:     obj,
			ParentName: model.SIEMAlertNodeName,
		},
	)
}

func (r *Resolver) SIEMAlertNode() graph.SIEMAlertNodeResolver { return &sIEMAlertNodeResolver{r} }

type sIEMAlertNodeResolver struct{ *Resolver }
