---
version: 2
updates:
  # Dependabot for go
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      # If you'd like a different schedule feel free to increase the frequency
      # or remove the "schedule" section altogether.
      interval: "weekly"
      # Dependabot runs sometime on Thursdays, so results are available on
      # Fridays, regardless of timezone. We _could_ run at a specific early
      # Friday time, but then everyone would run at the same time.
      day: "monday"
    groups:
      go-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  # Dependabot for docker
  - package-ecosystem: docker
    directory: "/"
    schedule:
      # If you'd like a different schedule feel free to increase the frequency
      # or remove the "schedule" section altogether.
      interval: "weekly"
      # Dependabot runs sometime on Thursdays, so results are available on
      # Fridays, regardless of timezone. We _could_ run at a specific early
      # Friday time, but then everyone would run at the same time.
      day: "monday"
    groups:
      docker-images:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  # Dependabot for actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      # If you'd like a different schedule feel free to increase the frequency
      # or remove the "schedule" section altogether.
      interval: "weekly"
      # Dependabot runs sometime on Thursdays, so results are available on
      # Fridays, regardless of timezone. We _could_ run at a specific early
      # Friday time, but then everyone would run at the same time.
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
