# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  disable-all: true
  enable:
    - errcheck
    - wsl_v5
    - unused
    - staticcheck
    - lll
  settings:
    staticcheck:
      checks: ["all", "-SA1019", "-ST1000", "-ST1003", "-ST1021", "-ST1020", "-ST1022", "-ST1001", "-SA1029"]
    govet:
      disable:
        - structtag
    errcheck:
      exclude-functions:
        - (io.Writer).Write
        - io.Copy
        - net.Conn.Close
    lll:
      line-length: 140
  exclusions:
      paths:
        - internal/mocks/
      rules:
        - path: _test\.go
          linters:
            - errcheck
            - lll
        - path: internal/api/graphql/graph/resolver/*
          linters:
            - lll
formatters:
  enable:
   - gofumpt
linters-settings:
  exhaustive:
    check-generated: false