version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - gocritic
    - gosec
    - errcheck
    - unused
    - unconvert
    - goconst
