# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

with-expecter: True # Create expecter methods: https://vektra.github.io/mockery/latest/features/#expecter-structs
dir: ./internal/mocks
filename: "mock_{{.InterfaceName}}.go"
outpkg: "mocks"
packages:
  github.wdf.sap.corp/cc/heureka/internal/database:
    interfaces:
      Database:
  github.wdf.sap.corp/cc/heureka/internal/app:
    interfaces:
      Heureka: