# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

dir: ./internal/mocks
filename: "mock_{{.InterfaceName}}.go"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/cloudoperators/heureka/internal/database:
    interfaces:
      Database: {}
  github.com/cloudoperators/heureka/internal/app:
    interfaces:
      Heureka: {}
  github.com/cloudoperators/heureka/internal/openfga:
    interfaces:
      Authorization: {}
