# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt via make
        entry: make fmt
        language: system
        types: [go]
        pass_filenames: false

      - id: go-lint
        name: go lint via make
        entry: make lint
        language: system
        types: [go]
        pass_filenames: false