FROM golang:1.23.1 AS builder

WORKDIR /go/src/github.com/cloudoperators/heureka

ADD . .
RUN CGO_ENABLED=0 go build -o /go/bin/heureka-scanner-nvd scanner/nvd/main.go

FROM gcr.io/distroless/static-debian12:nonroot

LABEL source_repository="https://github.com/cloudoperators/heureka"
LABEL source_folder="scanner/nvd"
USER nonroot:nonroot

COPY --from=builder /go/bin/heureka-scanner-nvd  /
ENTRYPOINT ["/heureka-scanner-nvd"]
