# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

query GetIssues ($filter: IssueFilter) {
  Issues (
    filter: $filter,
  ) {
    totalCount
    edges {
      node {
        id
        primaryName
        description
        type
        issueVariants(first: 1) {
          edges {
            node {
              id
              secondaryName
              severity {
                cvss {
                  vector
                }
              }
            }
          }
        }
      }
    }
  }
}
