// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"os"
	"text/template"
)

const maxArgs = 10

const tpl = `
{{range .}}
func WrapContext{{.N}}[{{.TypeParams}}, R any](
	ctx context.Context,
	f func(context.Context, {{.ArgsTypes}}) (R, error),
) func({{.ArgsTypes}}) (R, error) {
	return func({{.ArgsWithNames}}) (R, error) {
		return f(ctx, {{.ArgsNames}})
	}
}
{{end}}
`

type Data struct {
	N             int
	TypeParams    string
	ArgsTypes     string
	ArgsWithNames string
	ArgsNames     string
}

//nolint:errcheck
func main() {
	var data []Data

	for n := 1; n <= maxArgs; n++ {
		var typeParams, argsTypes, argsWithNames, argsNames string

		for i := 1; i <= n; i++ {
			if i > 1 {
				typeParams += ", "
				argsTypes += ", "
				argsWithNames += ", "
				argsNames += ", "
			}

			typeParams += fmt.Sprintf("A%d any", i)
			argsTypes += fmt.Sprintf("A%d", i)
			argsWithNames += fmt.Sprintf("a%d A%d", i, i)
			argsNames += fmt.Sprintf("a%d", i)
		}

		data = append(data, Data{
			N:             n,
			TypeParams:    typeParams,
			ArgsTypes:     argsTypes,
			ArgsWithNames: argsWithNames,
			ArgsNames:     argsNames,
		})
	}

	f, err := os.Create("context_wrapper_gen.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(f, "package cache")
	fmt.Fprintln(f, "import \"context\"")

	t := template.Must(template.New("").Parse(tpl))
	if err := t.Execute(f, data); err != nil {
		panic(err)
	}
}
