# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: "{{ .Values.scanner.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: config-volume
            configMap:
              name: {{ .Release.Name }}-configmap
          containers:
          - name: {{ .Release.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:
            - name: config-volume
              mountPath: "{{ .Values.scanner.config_mount_path }}"
              readOnly: true
            env:
              - name: HEUREKA_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-secret
                    key: api_token
              - name: HEUREKA_URL
                value: {{ .Values.scanner.heureka_url }}
              - name: SUPPORT_GROUP_LABEL
                value: {{ .Values.scanner.support_group_label }}
              - name: SERVICE_CCRN_LABEL
                value: {{ .Values.scanner.service_label }}
              - name: SCANNER_TIMEOUT
                value: {{ .Values.scanner.scanner_timeout }}
              - name: HEUREKA_CLUSTER_NAME
                value: {{ .Values.scanner.k8s_cluster_name }}
              - name: HEUREKA_CLUSTER_REGION
                value: {{ .Values.scanner.k8s_cluster_region }}
              - name: KUBE_CONFIG_TYPE
                value: "in-cluster"
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure