# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

input SIEMAlertLinkInput {
    name: String! @constraint(maxLength: 255)
    url: String! @constraint(maxLength: 2048, format: "url")
}

input SIEMAlertUpdateInput {
    status: IssueMatchStatusValues
    assigneeId: ID
}

input SIEMAlertInput {
    name: String @constraint(maxLength: 255)
    description: String @constraint(maxLength: 4096)
    severity: SeverityValues
    links: [SIEMAlertLinkInput]
    service: String @constraint(maxLength: 255)
    supportGroup: String @constraint(maxLength: 255)
    region: String @constraint(maxLength: 255)
    cluster: String @constraint(maxLength: 255)
    namespace: String @constraint(maxLength: 255)
    pod: String @constraint(maxLength: 255)
    container: String @constraint(maxLength: 255)
    source: String @constraint(maxLength: 255)
    acknowledged: Boolean
}

type SIEMAlertLink {
    name: String!
    url: String!
}

type SIEMAlert {
    name: String
    description: String
    severity: SeverityValues
    links: [SIEMAlertLink]
    service: String
    supportGroup: String
    region: String
    cluster: String
    namespace: String
    pod: String
    container: String
    source: String
}

type SIEMAlertNode implements Node {
    id: ID!
    name: String
    description: String
    severity: SeverityValues
    links: [SIEMAlertLink]
    service: String
    supportGroup: String
    region: String
    cluster: String
    namespace: String
    pod: String
    container: String
    source: String
    status: IssueMatchStatusValues
    discoveryDate: DateTime
    acknowledged: Boolean
    comments(filter: SIEMAlertCommentFilter, first: Int, after: String): SIEMAlertCommentConnection
}

type SIEMAlertConnection implements Connection {
    totalCount: Int!
    edges: [SIEMAlertEdge]
    pageInfo: PageInfo
}

type SIEMAlertEdge implements Edge {
    node: SIEMAlertNode!
    cursor: String
}

input SIEMAlertFilter {
    name: [String]
    severity: [SeverityValues]
    service: [String]
    status: [IssueMatchStatusValues]
    supportGroup: [String]
    region: [String]
    acknowledged: Boolean
}

input SIEMAlertOrderBy {
    by: SIEMAlertOrderByField
    direction: OrderDirection
}

enum SIEMAlertOrderByField {
    severity
    discoveryDate
}
