# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

input SIEMAlertInput {
    name: String
    description: String
    severity: SeverityValues
    url: String
    service: String
    supportGroup: String
    region: String
    cluster: String
    namespace: String
    pod: String
    container: String
    source: String
}

type SIEMAlert {
    name: String
    description: String
    severity: SeverityValues
    url: String
    service: String
    supportGroup: String
    region: String
    cluster: String
    namespace: String
    pod: String
    container: String
    source: String
}

type SIEMAlertNode implements Node {
    id: ID!
    name: String
    description: String
    severity: SeverityValues
    url: String
    service: String
    supportGroup: String
    region: String
    cluster: String
    namespace: String
    pod: String
    container: String
    source: String
    status: IssueMatchStatusValues
    discoveryDate: DateTime
    comments(filter: SIEMAlertCommentFilter, first: Int, after: String): SIEMAlertCommentConnection
}

type SIEMAlertConnection implements Connection {
    totalCount: Int!
    edges: [SIEMAlertEdge]
    pageInfo: PageInfo
}

type SIEMAlertEdge implements Edge {
    node: SIEMAlertNode!
    cursor: String
}

input SIEMAlertFilter {
    severity: [SeverityValues]
    service: [String]
    status: [IssueMatchStatusValues]
    supportGroup: [String]
    region: [String]
}

input SIEMAlertOrderBy {
    by: SIEMAlertOrderByField
    direction: OrderDirection
}

enum SIEMAlertOrderByField {
    severity
}
