# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

query ($filter: SIEMAlertFilter, $first: Int, $after: String, $orderBy: [SIEMAlertOrderBy]) {
    SIEMAlerts (
        filter: $filter,
        first: $first,
        after: $after
        orderBy: $orderBy
    ) {
        totalCount
        edges {
            node {
                id
                name
                description
                severity
                status
                discoveryDate
                service
                supportGroup
                region
                cluster
                namespace
                pod
                container
                source
            }
            cursor
        }
        pageInfo {
            hasNextPage
            hasPreviousPage
            isValidPage
            pageNumber
            nextPageAfter
            pages {
                after
                isCurrent
                pageNumber
                pageCount
            }
        }
    }
}
