apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heureka.fullname" . }}
  labels:
    {{- include "heureka.labels" . | nindent 4 }}
data: 
  environment: {{ .Values.environment | b64enc | quote }} 
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc }}
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc }}