# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - ../internal/database/mariadb/init/schema.sql:/app_sqlschema/schema.sql

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mariadb

    environment:
      # MariaDB Connection
      DB_ADDRESS: mariadb
      DB_PORT: 3306
      DB_USER: mariadb
      DB_PASSWORD: mariadb
      DB_ROOT_PASSWORD: mariadb
      DB_NAME: heureka
      DB_SCHEMA: /app_sqlschema/schema.sql


      SEED_MODE: true
      AUTH_TYPE: token
      AUTH_TOKEN_SECRET: xxx

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    
    environment:
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
      MARIADB_DATABASE: heureka
      MARIADB_ROOT_PASSWORD: mariadb

    volumes:
      - ../.mariadb-dev/:/var/lib/mysql
