# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

FROM mcr.microsoft.com/devcontainers/go

WORKDIR /go/src/github.com/cloudoperators/heureka
ADD . .
