# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

# Default values for keppel-scanner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scanner:
  api_token: ""
  heureka_url: ""
  schedule: "0 * * * *"
  keppel:
    username: ""
    password: ""
    fqdn: ""
    domain: ""
    project: ""
    user_domain: ""
  identity_endpoint: ""


image:
  repository: ghcr.io/cloudoperators/heureka-scanner-keppel
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""