# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: "{{ .Values.scanner.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: HEUREKA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: api_token
            - name: HEUREKA_URL
              value: {{ .Values.scanner.heureka_url }}
            - name: NVDSERVER_URL
              value: {{ .Values.scanner.nvd.api_url }}
            - name: NVD_API_KEY
              valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-secret
                    key: nvd_api_key
            - name: NVD_RESULTS_PER_PAGE
              value: {{ .Values.scanner.nvd.results_per_page }}
            - name: NVD_START_DATE
              value: {{ .Values.scanner.nvd.start_date }}
            - name: NVD_END_DATE
              value: {{ .Values.scanner.nvd.end_date }}
          restartPolicy: OnFailure