# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  api_token: {{ .Values.scanner.heureka.api_token | b64enc }}
  keppel_username: {{ .Values.scanner.keppel.username | b64enc }}
  keppel_password: {{ .Values.scanner.keppel.password | b64enc }}