// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// AddComponentVersionToIssueResponse is returned by AddComponentVersionToIssue on success.
type AddComponentVersionToIssueResponse struct {
	AddComponentVersionToIssue *Issue `json:"addComponentVersionToIssue"`
}

// GetAddComponentVersionToIssue returns AddComponentVersionToIssueResponse.AddComponentVersionToIssue, and is useful for accessing the field via an interface.
func (v *AddComponentVersionToIssueResponse) GetAddComponentVersionToIssue() *Issue {
	return v.AddComponentVersionToIssue
}

// AddServiceToSupportGroupResponse is returned by AddServiceToSupportGroup on success.
type AddServiceToSupportGroupResponse struct {
	AddServiceToSupportGroup *SupportGroup `json:"addServiceToSupportGroup"`
}

// GetAddServiceToSupportGroup returns AddServiceToSupportGroupResponse.AddServiceToSupportGroup, and is useful for accessing the field via an interface.
func (v *AddServiceToSupportGroupResponse) GetAddServiceToSupportGroup() *SupportGroup {
	return v.AddServiceToSupportGroup
}

// Component includes the requested fields of the GraphQL type Component.
type Component struct {
	Id   string              `json:"id"`
	Ccrn string              `json:"ccrn"`
	Type ComponentTypeValues `json:"type"`
}

// GetId returns Component.Id, and is useful for accessing the field via an interface.
func (v *Component) GetId() string { return v.Id }

// GetCcrn returns Component.Ccrn, and is useful for accessing the field via an interface.
func (v *Component) GetCcrn() string { return v.Ccrn }

// GetType returns Component.Type, and is useful for accessing the field via an interface.
func (v *Component) GetType() ComponentTypeValues { return v.Type }

// ComponentAggregate includes the requested fields of the GraphQL type Component.
type ComponentAggregate struct {
	Id                string              `json:"id"`
	Ccrn              string              `json:"ccrn"`
	Type              ComponentTypeValues `json:"type"`
	ComponentVersions *ComponentVersions  `json:"componentVersions"`
}

// GetId returns ComponentAggregate.Id, and is useful for accessing the field via an interface.
func (v *ComponentAggregate) GetId() string { return v.Id }

// GetCcrn returns ComponentAggregate.Ccrn, and is useful for accessing the field via an interface.
func (v *ComponentAggregate) GetCcrn() string { return v.Ccrn }

// GetType returns ComponentAggregate.Type, and is useful for accessing the field via an interface.
func (v *ComponentAggregate) GetType() ComponentTypeValues { return v.Type }

// GetComponentVersions returns ComponentAggregate.ComponentVersions, and is useful for accessing the field via an interface.
func (v *ComponentAggregate) GetComponentVersions() *ComponentVersions { return v.ComponentVersions }

// ComponentConnection includes the requested fields of the GraphQL type ComponentConnection.
type ComponentConnection struct {
	TotalCount int                                      `json:"totalCount"`
	Edges      []*ComponentConnectionEdgesComponentEdge `json:"edges"`
}

// GetTotalCount returns ComponentConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *ComponentConnection) GetTotalCount() int { return v.TotalCount }

// GetEdges returns ComponentConnection.Edges, and is useful for accessing the field via an interface.
func (v *ComponentConnection) GetEdges() []*ComponentConnectionEdgesComponentEdge { return v.Edges }

// ComponentConnectionEdgesComponentEdge includes the requested fields of the GraphQL type ComponentEdge.
type ComponentConnectionEdgesComponentEdge struct {
	Node   *ComponentAggregate `json:"node"`
	Cursor string              `json:"cursor"`
}

// GetNode returns ComponentConnectionEdgesComponentEdge.Node, and is useful for accessing the field via an interface.
func (v *ComponentConnectionEdgesComponentEdge) GetNode() *ComponentAggregate { return v.Node }

// GetCursor returns ComponentConnectionEdgesComponentEdge.Cursor, and is useful for accessing the field via an interface.
func (v *ComponentConnectionEdgesComponentEdge) GetCursor() string { return v.Cursor }

type ComponentFilter struct {
	ComponentCcrn []string `json:"componentCcrn"`
}

// GetComponentCcrn returns ComponentFilter.ComponentCcrn, and is useful for accessing the field via an interface.
func (v *ComponentFilter) GetComponentCcrn() []string { return v.ComponentCcrn }

type ComponentInput struct {
	Ccrn string              `json:"ccrn"`
	Type ComponentTypeValues `json:"type"`
}

// GetCcrn returns ComponentInput.Ccrn, and is useful for accessing the field via an interface.
func (v *ComponentInput) GetCcrn() string { return v.Ccrn }

// GetType returns ComponentInput.Type, and is useful for accessing the field via an interface.
func (v *ComponentInput) GetType() ComponentTypeValues { return v.Type }

// ComponentInstance includes the requested fields of the GraphQL type ComponentInstance.
type ComponentInstance struct {
	Id                 string `json:"id"`
	Ccrn               string `json:"ccrn"`
	Count              int    `json:"count"`
	ComponentVersionId string `json:"componentVersionId"`
	ServiceId          string `json:"serviceId"`
}

// GetId returns ComponentInstance.Id, and is useful for accessing the field via an interface.
func (v *ComponentInstance) GetId() string { return v.Id }

// GetCcrn returns ComponentInstance.Ccrn, and is useful for accessing the field via an interface.
func (v *ComponentInstance) GetCcrn() string { return v.Ccrn }

// GetCount returns ComponentInstance.Count, and is useful for accessing the field via an interface.
func (v *ComponentInstance) GetCount() int { return v.Count }

// GetComponentVersionId returns ComponentInstance.ComponentVersionId, and is useful for accessing the field via an interface.
func (v *ComponentInstance) GetComponentVersionId() string { return v.ComponentVersionId }

// GetServiceId returns ComponentInstance.ServiceId, and is useful for accessing the field via an interface.
func (v *ComponentInstance) GetServiceId() string { return v.ServiceId }

type ComponentInstanceFilter struct {
	ServiceCcrn  []string `json:"serviceCcrn"`
	Ccrn         []string `json:"ccrn"`
	SupportGroup []string `json:"supportGroup"`
	Search       []string `json:"search"`
}

// GetServiceCcrn returns ComponentInstanceFilter.ServiceCcrn, and is useful for accessing the field via an interface.
func (v *ComponentInstanceFilter) GetServiceCcrn() []string { return v.ServiceCcrn }

// GetCcrn returns ComponentInstanceFilter.Ccrn, and is useful for accessing the field via an interface.
func (v *ComponentInstanceFilter) GetCcrn() []string { return v.Ccrn }

// GetSupportGroup returns ComponentInstanceFilter.SupportGroup, and is useful for accessing the field via an interface.
func (v *ComponentInstanceFilter) GetSupportGroup() []string { return v.SupportGroup }

// GetSearch returns ComponentInstanceFilter.Search, and is useful for accessing the field via an interface.
func (v *ComponentInstanceFilter) GetSearch() []string { return v.Search }

type ComponentInstanceInput struct {
	Ccrn               string `json:"ccrn"`
	Count              int    `json:"count"`
	ComponentVersionId string `json:"componentVersionId"`
	ServiceId          string `json:"serviceId"`
}

// GetCcrn returns ComponentInstanceInput.Ccrn, and is useful for accessing the field via an interface.
func (v *ComponentInstanceInput) GetCcrn() string { return v.Ccrn }

// GetCount returns ComponentInstanceInput.Count, and is useful for accessing the field via an interface.
func (v *ComponentInstanceInput) GetCount() int { return v.Count }

// GetComponentVersionId returns ComponentInstanceInput.ComponentVersionId, and is useful for accessing the field via an interface.
func (v *ComponentInstanceInput) GetComponentVersionId() string { return v.ComponentVersionId }

// GetServiceId returns ComponentInstanceInput.ServiceId, and is useful for accessing the field via an interface.
func (v *ComponentInstanceInput) GetServiceId() string { return v.ServiceId }

type ComponentTypeValues string

const (
	ComponentTypeValuesContainerimage      ComponentTypeValues = "containerImage"
	ComponentTypeValuesVirtualmachineimage ComponentTypeValues = "virtualMachineImage"
	ComponentTypeValuesRepository          ComponentTypeValues = "repository"
)

// ComponentVersion includes the requested fields of the GraphQL type ComponentVersion.
type ComponentVersion struct {
	Id          string `json:"id"`
	Version     string `json:"version"`
	ComponentId string `json:"componentId"`
}

// GetId returns ComponentVersion.Id, and is useful for accessing the field via an interface.
func (v *ComponentVersion) GetId() string { return v.Id }

// GetVersion returns ComponentVersion.Version, and is useful for accessing the field via an interface.
func (v *ComponentVersion) GetVersion() string { return v.Version }

// GetComponentId returns ComponentVersion.ComponentId, and is useful for accessing the field via an interface.
func (v *ComponentVersion) GetComponentId() string { return v.ComponentId }

// ComponentVersionConnection includes the requested fields of the GraphQL type ComponentVersionConnection.
type ComponentVersionConnection struct {
	Edges []*ComponentVersionConnectionEdgesComponentVersionEdge `json:"edges"`
}

// GetEdges returns ComponentVersionConnection.Edges, and is useful for accessing the field via an interface.
func (v *ComponentVersionConnection) GetEdges() []*ComponentVersionConnectionEdgesComponentVersionEdge {
	return v.Edges
}

// ComponentVersionConnectionEdgesComponentVersionEdge includes the requested fields of the GraphQL type ComponentVersionEdge.
type ComponentVersionConnectionEdgesComponentVersionEdge struct {
	Node *ComponentVersion `json:"node"`
}

// GetNode returns ComponentVersionConnectionEdgesComponentVersionEdge.Node, and is useful for accessing the field via an interface.
func (v *ComponentVersionConnectionEdgesComponentVersionEdge) GetNode() *ComponentVersion {
	return v.Node
}

type ComponentVersionFilter struct {
	ComponentId   []string `json:"componentId"`
	ComponentCcrn []string `json:"componentCcrn"`
	IssueId       []string `json:"issueId"`
	Version       []string `json:"version"`
}

// GetComponentId returns ComponentVersionFilter.ComponentId, and is useful for accessing the field via an interface.
func (v *ComponentVersionFilter) GetComponentId() []string { return v.ComponentId }

// GetComponentCcrn returns ComponentVersionFilter.ComponentCcrn, and is useful for accessing the field via an interface.
func (v *ComponentVersionFilter) GetComponentCcrn() []string { return v.ComponentCcrn }

// GetIssueId returns ComponentVersionFilter.IssueId, and is useful for accessing the field via an interface.
func (v *ComponentVersionFilter) GetIssueId() []string { return v.IssueId }

// GetVersion returns ComponentVersionFilter.Version, and is useful for accessing the field via an interface.
func (v *ComponentVersionFilter) GetVersion() []string { return v.Version }

type ComponentVersionInput struct {
	Version     string `json:"version"`
	ComponentId string `json:"componentId"`
}

// GetVersion returns ComponentVersionInput.Version, and is useful for accessing the field via an interface.
func (v *ComponentVersionInput) GetVersion() string { return v.Version }

// GetComponentId returns ComponentVersionInput.ComponentId, and is useful for accessing the field via an interface.
func (v *ComponentVersionInput) GetComponentId() string { return v.ComponentId }

// ComponentVersions includes the requested fields of the GraphQL type ComponentVersionConnection.
type ComponentVersions struct {
	Edges []*ComponentVersionsEdgesComponentVersionEdge `json:"edges"`
}

// GetEdges returns ComponentVersions.Edges, and is useful for accessing the field via an interface.
func (v *ComponentVersions) GetEdges() []*ComponentVersionsEdgesComponentVersionEdge { return v.Edges }

// ComponentVersionsEdgesComponentVersionEdge includes the requested fields of the GraphQL type ComponentVersionEdge.
type ComponentVersionsEdgesComponentVersionEdge struct {
	Node *ComponentVersion `json:"node"`
}

// GetNode returns ComponentVersionsEdgesComponentVersionEdge.Node, and is useful for accessing the field via an interface.
func (v *ComponentVersionsEdgesComponentVersionEdge) GetNode() *ComponentVersion { return v.Node }

// CreateComponentInstanceResponse is returned by CreateComponentInstance on success.
type CreateComponentInstanceResponse struct {
	CreateComponentInstance *ComponentInstance `json:"createComponentInstance"`
}

// GetCreateComponentInstance returns CreateComponentInstanceResponse.CreateComponentInstance, and is useful for accessing the field via an interface.
func (v *CreateComponentInstanceResponse) GetCreateComponentInstance() *ComponentInstance {
	return v.CreateComponentInstance
}

// CreateComponentResponse is returned by CreateComponent on success.
type CreateComponentResponse struct {
	CreateComponent *Component `json:"createComponent"`
}

// GetCreateComponent returns CreateComponentResponse.CreateComponent, and is useful for accessing the field via an interface.
func (v *CreateComponentResponse) GetCreateComponent() *Component { return v.CreateComponent }

// CreateComponentVersionResponse is returned by CreateComponentVersion on success.
type CreateComponentVersionResponse struct {
	CreateComponentVersion *ComponentVersion `json:"createComponentVersion"`
}

// GetCreateComponentVersion returns CreateComponentVersionResponse.CreateComponentVersion, and is useful for accessing the field via an interface.
func (v *CreateComponentVersionResponse) GetCreateComponentVersion() *ComponentVersion {
	return v.CreateComponentVersion
}

// CreateIssueRepositoryCreateIssueRepository includes the requested fields of the GraphQL type IssueRepository.
type CreateIssueRepositoryCreateIssueRepository struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Url  string `json:"url"`
}

// GetId returns CreateIssueRepositoryCreateIssueRepository.Id, and is useful for accessing the field via an interface.
func (v *CreateIssueRepositoryCreateIssueRepository) GetId() string { return v.Id }

// GetName returns CreateIssueRepositoryCreateIssueRepository.Name, and is useful for accessing the field via an interface.
func (v *CreateIssueRepositoryCreateIssueRepository) GetName() string { return v.Name }

// GetUrl returns CreateIssueRepositoryCreateIssueRepository.Url, and is useful for accessing the field via an interface.
func (v *CreateIssueRepositoryCreateIssueRepository) GetUrl() string { return v.Url }

// CreateIssueRepositoryResponse is returned by CreateIssueRepository on success.
type CreateIssueRepositoryResponse struct {
	CreateIssueRepository *CreateIssueRepositoryCreateIssueRepository `json:"createIssueRepository"`
}

// GetCreateIssueRepository returns CreateIssueRepositoryResponse.CreateIssueRepository, and is useful for accessing the field via an interface.
func (v *CreateIssueRepositoryResponse) GetCreateIssueRepository() *CreateIssueRepositoryCreateIssueRepository {
	return v.CreateIssueRepository
}

// CreateIssueResponse is returned by CreateIssue on success.
type CreateIssueResponse struct {
	CreateIssue *Issue `json:"createIssue"`
}

// GetCreateIssue returns CreateIssueResponse.CreateIssue, and is useful for accessing the field via an interface.
func (v *CreateIssueResponse) GetCreateIssue() *Issue { return v.CreateIssue }

// CreateServiceCreateService includes the requested fields of the GraphQL type Service.
type CreateServiceCreateService struct {
	Id   string `json:"id"`
	Ccrn string `json:"ccrn"`
}

// GetId returns CreateServiceCreateService.Id, and is useful for accessing the field via an interface.
func (v *CreateServiceCreateService) GetId() string { return v.Id }

// GetCcrn returns CreateServiceCreateService.Ccrn, and is useful for accessing the field via an interface.
func (v *CreateServiceCreateService) GetCcrn() string { return v.Ccrn }

// CreateServiceResponse is returned by CreateService on success.
type CreateServiceResponse struct {
	CreateService *CreateServiceCreateService `json:"createService"`
}

// GetCreateService returns CreateServiceResponse.CreateService, and is useful for accessing the field via an interface.
func (v *CreateServiceResponse) GetCreateService() *CreateServiceCreateService {
	return v.CreateService
}

// CreateSupportGroupResponse is returned by CreateSupportGroup on success.
type CreateSupportGroupResponse struct {
	CreateSupportGroup *SupportGroup `json:"createSupportGroup"`
}

// GetCreateSupportGroup returns CreateSupportGroupResponse.CreateSupportGroup, and is useful for accessing the field via an interface.
func (v *CreateSupportGroupResponse) GetCreateSupportGroup() *SupportGroup {
	return v.CreateSupportGroup
}

// Issue includes the requested fields of the GraphQL type Issue.
type Issue struct {
	Id          string     `json:"id"`
	PrimaryName string     `json:"primaryName"`
	Description string     `json:"description"`
	Type        IssueTypes `json:"type"`
}

// GetId returns Issue.Id, and is useful for accessing the field via an interface.
func (v *Issue) GetId() string { return v.Id }

// GetPrimaryName returns Issue.PrimaryName, and is useful for accessing the field via an interface.
func (v *Issue) GetPrimaryName() string { return v.PrimaryName }

// GetDescription returns Issue.Description, and is useful for accessing the field via an interface.
func (v *Issue) GetDescription() string { return v.Description }

// GetType returns Issue.Type, and is useful for accessing the field via an interface.
func (v *Issue) GetType() IssueTypes { return v.Type }

// IssueConnection includes the requested fields of the GraphQL type IssueConnection.
type IssueConnection struct {
	Edges []*IssueConnectionEdgesIssueEdge `json:"edges"`
}

// GetEdges returns IssueConnection.Edges, and is useful for accessing the field via an interface.
func (v *IssueConnection) GetEdges() []*IssueConnectionEdgesIssueEdge { return v.Edges }

// IssueConnectionEdgesIssueEdge includes the requested fields of the GraphQL type IssueEdge.
type IssueConnectionEdgesIssueEdge struct {
	Node *Issue `json:"node"`
}

// GetNode returns IssueConnectionEdgesIssueEdge.Node, and is useful for accessing the field via an interface.
func (v *IssueConnectionEdgesIssueEdge) GetNode() *Issue { return v.Node }

type IssueFilter struct {
	AffectedService    []string                 `json:"affectedService"`
	PrimaryName        []string                 `json:"primaryName"`
	IssueMatchStatus   []IssueMatchStatusValues `json:"issueMatchStatus"`
	IssueType          []IssueTypes             `json:"issueType"`
	ComponentVersionId []string                 `json:"componentVersionId"`
	Search             []string                 `json:"search"`
}

// GetAffectedService returns IssueFilter.AffectedService, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetAffectedService() []string { return v.AffectedService }

// GetPrimaryName returns IssueFilter.PrimaryName, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetPrimaryName() []string { return v.PrimaryName }

// GetIssueMatchStatus returns IssueFilter.IssueMatchStatus, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetIssueMatchStatus() []IssueMatchStatusValues { return v.IssueMatchStatus }

// GetIssueType returns IssueFilter.IssueType, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetIssueType() []IssueTypes { return v.IssueType }

// GetComponentVersionId returns IssueFilter.ComponentVersionId, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetComponentVersionId() []string { return v.ComponentVersionId }

// GetSearch returns IssueFilter.Search, and is useful for accessing the field via an interface.
func (v *IssueFilter) GetSearch() []string { return v.Search }

type IssueInput struct {
	PrimaryName string     `json:"primaryName"`
	Description string     `json:"description"`
	Type        IssueTypes `json:"type"`
}

// GetPrimaryName returns IssueInput.PrimaryName, and is useful for accessing the field via an interface.
func (v *IssueInput) GetPrimaryName() string { return v.PrimaryName }

// GetDescription returns IssueInput.Description, and is useful for accessing the field via an interface.
func (v *IssueInput) GetDescription() string { return v.Description }

// GetType returns IssueInput.Type, and is useful for accessing the field via an interface.
func (v *IssueInput) GetType() IssueTypes { return v.Type }

type IssueMatchStatusValues string

const (
	IssueMatchStatusValuesNew           IssueMatchStatusValues = "new"
	IssueMatchStatusValuesRiskAccepted  IssueMatchStatusValues = "risk_accepted"
	IssueMatchStatusValuesFalsePositive IssueMatchStatusValues = "false_positive"
	IssueMatchStatusValuesMitigated     IssueMatchStatusValues = "mitigated"
)

type IssueRepositoryFilter struct {
	ServiceCcrn []string `json:"serviceCcrn"`
	ServiceId   []string `json:"serviceId"`
	Name        []string `json:"name"`
}

// GetServiceCcrn returns IssueRepositoryFilter.ServiceCcrn, and is useful for accessing the field via an interface.
func (v *IssueRepositoryFilter) GetServiceCcrn() []string { return v.ServiceCcrn }

// GetServiceId returns IssueRepositoryFilter.ServiceId, and is useful for accessing the field via an interface.
func (v *IssueRepositoryFilter) GetServiceId() []string { return v.ServiceId }

// GetName returns IssueRepositoryFilter.Name, and is useful for accessing the field via an interface.
func (v *IssueRepositoryFilter) GetName() []string { return v.Name }

type IssueRepositoryInput struct {
	Name string `json:"name"`
	Url  string `json:"url"`
}

// GetName returns IssueRepositoryInput.Name, and is useful for accessing the field via an interface.
func (v *IssueRepositoryInput) GetName() string { return v.Name }

// GetUrl returns IssueRepositoryInput.Url, and is useful for accessing the field via an interface.
func (v *IssueRepositoryInput) GetUrl() string { return v.Url }

type IssueTypes string

const (
	IssueTypesVulnerability   IssueTypes = "Vulnerability"
	IssueTypesPolicyviolation IssueTypes = "PolicyViolation"
	IssueTypesSecurityevent   IssueTypes = "SecurityEvent"
)

// ListComponentInstancesComponentInstancesComponentInstanceConnection includes the requested fields of the GraphQL type ComponentInstanceConnection.
type ListComponentInstancesComponentInstancesComponentInstanceConnection struct {
	TotalCount int                                                                                              `json:"totalCount"`
	Edges      []*ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdge `json:"edges"`
}

// GetTotalCount returns ListComponentInstancesComponentInstancesComponentInstanceConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *ListComponentInstancesComponentInstancesComponentInstanceConnection) GetTotalCount() int {
	return v.TotalCount
}

// GetEdges returns ListComponentInstancesComponentInstancesComponentInstanceConnection.Edges, and is useful for accessing the field via an interface.
func (v *ListComponentInstancesComponentInstancesComponentInstanceConnection) GetEdges() []*ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdge {
	return v.Edges
}

// ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdge includes the requested fields of the GraphQL type ComponentInstanceEdge.
type ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdge struct {
	Node *ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdgeNodeComponentInstance `json:"node"`
}

// GetNode returns ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdge.Node, and is useful for accessing the field via an interface.
func (v *ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdge) GetNode() *ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdgeNodeComponentInstance {
	return v.Node
}

// ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdgeNodeComponentInstance includes the requested fields of the GraphQL type ComponentInstance.
type ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdgeNodeComponentInstance struct {
	Id string `json:"id"`
}

// GetId returns ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdgeNodeComponentInstance.Id, and is useful for accessing the field via an interface.
func (v *ListComponentInstancesComponentInstancesComponentInstanceConnectionEdgesComponentInstanceEdgeNodeComponentInstance) GetId() string {
	return v.Id
}

// ListComponentInstancesResponse is returned by ListComponentInstances on success.
type ListComponentInstancesResponse struct {
	ComponentInstances *ListComponentInstancesComponentInstancesComponentInstanceConnection `json:"ComponentInstances"`
}

// GetComponentInstances returns ListComponentInstancesResponse.ComponentInstances, and is useful for accessing the field via an interface.
func (v *ListComponentInstancesResponse) GetComponentInstances() *ListComponentInstancesComponentInstancesComponentInstanceConnection {
	return v.ComponentInstances
}

// ListComponentVersionsResponse is returned by ListComponentVersions on success.
type ListComponentVersionsResponse struct {
	ComponentVersions *ComponentVersionConnection `json:"ComponentVersions"`
}

// GetComponentVersions returns ListComponentVersionsResponse.ComponentVersions, and is useful for accessing the field via an interface.
func (v *ListComponentVersionsResponse) GetComponentVersions() *ComponentVersionConnection {
	return v.ComponentVersions
}

// ListComponentsResponse is returned by ListComponents on success.
type ListComponentsResponse struct {
	Components *ComponentConnection `json:"Components"`
}

// GetComponents returns ListComponentsResponse.Components, and is useful for accessing the field via an interface.
func (v *ListComponentsResponse) GetComponents() *ComponentConnection { return v.Components }

// ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnection includes the requested fields of the GraphQL type IssueRepositoryConnection.
type ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnection struct {
	TotalCount int                                                                                        `json:"totalCount"`
	Edges      []*ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdge `json:"edges"`
}

// GetTotalCount returns ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnection) GetTotalCount() int {
	return v.TotalCount
}

// GetEdges returns ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnection.Edges, and is useful for accessing the field via an interface.
func (v *ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnection) GetEdges() []*ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdge {
	return v.Edges
}

// ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdge includes the requested fields of the GraphQL type IssueRepositoryEdge.
type ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdge struct {
	Node *ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdgeNodeIssueRepository `json:"node"`
}

// GetNode returns ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdge.Node, and is useful for accessing the field via an interface.
func (v *ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdge) GetNode() *ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdgeNodeIssueRepository {
	return v.Node
}

// ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdgeNodeIssueRepository includes the requested fields of the GraphQL type IssueRepository.
type ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdgeNodeIssueRepository struct {
	Id string `json:"id"`
}

// GetId returns ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdgeNodeIssueRepository.Id, and is useful for accessing the field via an interface.
func (v *ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnectionEdgesIssueRepositoryEdgeNodeIssueRepository) GetId() string {
	return v.Id
}

// ListIssueRepositoriesResponse is returned by ListIssueRepositories on success.
type ListIssueRepositoriesResponse struct {
	IssueRepositories *ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnection `json:"IssueRepositories"`
}

// GetIssueRepositories returns ListIssueRepositoriesResponse.IssueRepositories, and is useful for accessing the field via an interface.
func (v *ListIssueRepositoriesResponse) GetIssueRepositories() *ListIssueRepositoriesIssueRepositoriesIssueRepositoryConnection {
	return v.IssueRepositories
}

// ListIssuesResponse is returned by ListIssues on success.
type ListIssuesResponse struct {
	Issues *IssueConnection `json:"Issues"`
}

// GetIssues returns ListIssuesResponse.Issues, and is useful for accessing the field via an interface.
func (v *ListIssuesResponse) GetIssues() *IssueConnection { return v.Issues }

// ListServicesResponse is returned by ListServices on success.
type ListServicesResponse struct {
	Services *ListServicesServicesServiceConnection `json:"Services"`
}

// GetServices returns ListServicesResponse.Services, and is useful for accessing the field via an interface.
func (v *ListServicesResponse) GetServices() *ListServicesServicesServiceConnection {
	return v.Services
}

// ListServicesServicesServiceConnection includes the requested fields of the GraphQL type ServiceConnection.
type ListServicesServicesServiceConnection struct {
	TotalCount int                                                      `json:"totalCount"`
	Edges      []*ListServicesServicesServiceConnectionEdgesServiceEdge `json:"edges"`
}

// GetTotalCount returns ListServicesServicesServiceConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnection) GetTotalCount() int { return v.TotalCount }

// GetEdges returns ListServicesServicesServiceConnection.Edges, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnection) GetEdges() []*ListServicesServicesServiceConnectionEdgesServiceEdge {
	return v.Edges
}

// ListServicesServicesServiceConnectionEdgesServiceEdge includes the requested fields of the GraphQL type ServiceEdge.
type ListServicesServicesServiceConnectionEdgesServiceEdge struct {
	Node *ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService `json:"node"`
}

// GetNode returns ListServicesServicesServiceConnectionEdgesServiceEdge.Node, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnectionEdgesServiceEdge) GetNode() *ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService {
	return v.Node
}

// ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService includes the requested fields of the GraphQL type Service.
type ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService struct {
	Id string `json:"id"`
}

// GetId returns ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService.Id, and is useful for accessing the field via an interface.
func (v *ListServicesServicesServiceConnectionEdgesServiceEdgeNodeService) GetId() string {
	return v.Id
}

// ListSupportGroupsResponse is returned by ListSupportGroups on success.
type ListSupportGroupsResponse struct {
	SupportGroups *ListSupportGroupsSupportGroupsSupportGroupConnection `json:"SupportGroups"`
}

// GetSupportGroups returns ListSupportGroupsResponse.SupportGroups, and is useful for accessing the field via an interface.
func (v *ListSupportGroupsResponse) GetSupportGroups() *ListSupportGroupsSupportGroupsSupportGroupConnection {
	return v.SupportGroups
}

// ListSupportGroupsSupportGroupsSupportGroupConnection includes the requested fields of the GraphQL type SupportGroupConnection.
type ListSupportGroupsSupportGroupsSupportGroupConnection struct {
	TotalCount int                                                                          `json:"totalCount"`
	Edges      []*ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdge `json:"edges"`
}

// GetTotalCount returns ListSupportGroupsSupportGroupsSupportGroupConnection.TotalCount, and is useful for accessing the field via an interface.
func (v *ListSupportGroupsSupportGroupsSupportGroupConnection) GetTotalCount() int {
	return v.TotalCount
}

// GetEdges returns ListSupportGroupsSupportGroupsSupportGroupConnection.Edges, and is useful for accessing the field via an interface.
func (v *ListSupportGroupsSupportGroupsSupportGroupConnection) GetEdges() []*ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdge {
	return v.Edges
}

// ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdge includes the requested fields of the GraphQL type SupportGroupEdge.
type ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdge struct {
	Node *ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdgeNodeSupportGroup `json:"node"`
}

// GetNode returns ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdge.Node, and is useful for accessing the field via an interface.
func (v *ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdge) GetNode() *ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdgeNodeSupportGroup {
	return v.Node
}

// ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdgeNodeSupportGroup includes the requested fields of the GraphQL type SupportGroup.
type ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdgeNodeSupportGroup struct {
	Id string `json:"id"`
}

// GetId returns ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdgeNodeSupportGroup.Id, and is useful for accessing the field via an interface.
func (v *ListSupportGroupsSupportGroupsSupportGroupConnectionEdgesSupportGroupEdgeNodeSupportGroup) GetId() string {
	return v.Id
}

type ServiceFilter struct {
	ServiceCcrn      []string `json:"serviceCcrn"`
	UniqueUserId     []string `json:"uniqueUserId"`
	Type             []int    `json:"type"`
	UserName         []string `json:"userName"`
	SupportGroupCcrn []string `json:"supportGroupCcrn"`
	Search           []string `json:"search"`
}

// GetServiceCcrn returns ServiceFilter.ServiceCcrn, and is useful for accessing the field via an interface.
func (v *ServiceFilter) GetServiceCcrn() []string { return v.ServiceCcrn }

// GetUniqueUserId returns ServiceFilter.UniqueUserId, and is useful for accessing the field via an interface.
func (v *ServiceFilter) GetUniqueUserId() []string { return v.UniqueUserId }

// GetType returns ServiceFilter.Type, and is useful for accessing the field via an interface.
func (v *ServiceFilter) GetType() []int { return v.Type }

// GetUserName returns ServiceFilter.UserName, and is useful for accessing the field via an interface.
func (v *ServiceFilter) GetUserName() []string { return v.UserName }

// GetSupportGroupCcrn returns ServiceFilter.SupportGroupCcrn, and is useful for accessing the field via an interface.
func (v *ServiceFilter) GetSupportGroupCcrn() []string { return v.SupportGroupCcrn }

// GetSearch returns ServiceFilter.Search, and is useful for accessing the field via an interface.
func (v *ServiceFilter) GetSearch() []string { return v.Search }

type ServiceInput struct {
	Ccrn string `json:"ccrn"`
}

// GetCcrn returns ServiceInput.Ccrn, and is useful for accessing the field via an interface.
func (v *ServiceInput) GetCcrn() string { return v.Ccrn }

// SupportGroup includes the requested fields of the GraphQL type SupportGroup.
type SupportGroup struct {
	Id   string `json:"id"`
	Ccrn string `json:"ccrn"`
}

// GetId returns SupportGroup.Id, and is useful for accessing the field via an interface.
func (v *SupportGroup) GetId() string { return v.Id }

// GetCcrn returns SupportGroup.Ccrn, and is useful for accessing the field via an interface.
func (v *SupportGroup) GetCcrn() string { return v.Ccrn }

type SupportGroupFilter struct {
	SupportGroupCcrn []string `json:"supportGroupCcrn"`
	UserIds          []string `json:"userIds"`
}

// GetSupportGroupCcrn returns SupportGroupFilter.SupportGroupCcrn, and is useful for accessing the field via an interface.
func (v *SupportGroupFilter) GetSupportGroupCcrn() []string { return v.SupportGroupCcrn }

// GetUserIds returns SupportGroupFilter.UserIds, and is useful for accessing the field via an interface.
func (v *SupportGroupFilter) GetUserIds() []string { return v.UserIds }

type SupportGroupInput struct {
	Ccrn string `json:"ccrn"`
}

// GetCcrn returns SupportGroupInput.Ccrn, and is useful for accessing the field via an interface.
func (v *SupportGroupInput) GetCcrn() string { return v.Ccrn }

// __AddComponentVersionToIssueInput is used internally by genqlient
type __AddComponentVersionToIssueInput struct {
	IssueId            string `json:"issueId"`
	ComponentVersionId string `json:"componentVersionId"`
}

// GetIssueId returns __AddComponentVersionToIssueInput.IssueId, and is useful for accessing the field via an interface.
func (v *__AddComponentVersionToIssueInput) GetIssueId() string { return v.IssueId }

// GetComponentVersionId returns __AddComponentVersionToIssueInput.ComponentVersionId, and is useful for accessing the field via an interface.
func (v *__AddComponentVersionToIssueInput) GetComponentVersionId() string {
	return v.ComponentVersionId
}

// __AddServiceToSupportGroupInput is used internally by genqlient
type __AddServiceToSupportGroupInput struct {
	SupportGroupId string `json:"supportGroupId"`
	ServiceId      string `json:"serviceId"`
}

// GetSupportGroupId returns __AddServiceToSupportGroupInput.SupportGroupId, and is useful for accessing the field via an interface.
func (v *__AddServiceToSupportGroupInput) GetSupportGroupId() string { return v.SupportGroupId }

// GetServiceId returns __AddServiceToSupportGroupInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__AddServiceToSupportGroupInput) GetServiceId() string { return v.ServiceId }

// __CreateComponentInput is used internally by genqlient
type __CreateComponentInput struct {
	Input *ComponentInput `json:"input,omitempty"`
}

// GetInput returns __CreateComponentInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateComponentInput) GetInput() *ComponentInput { return v.Input }

// __CreateComponentInstanceInput is used internally by genqlient
type __CreateComponentInstanceInput struct {
	Input *ComponentInstanceInput `json:"input,omitempty"`
}

// GetInput returns __CreateComponentInstanceInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateComponentInstanceInput) GetInput() *ComponentInstanceInput { return v.Input }

// __CreateComponentVersionInput is used internally by genqlient
type __CreateComponentVersionInput struct {
	Input *ComponentVersionInput `json:"input,omitempty"`
}

// GetInput returns __CreateComponentVersionInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateComponentVersionInput) GetInput() *ComponentVersionInput { return v.Input }

// __CreateIssueInput is used internally by genqlient
type __CreateIssueInput struct {
	Input *IssueInput `json:"input,omitempty"`
}

// GetInput returns __CreateIssueInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateIssueInput) GetInput() *IssueInput { return v.Input }

// __CreateIssueRepositoryInput is used internally by genqlient
type __CreateIssueRepositoryInput struct {
	Input *IssueRepositoryInput `json:"input,omitempty"`
}

// GetInput returns __CreateIssueRepositoryInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateIssueRepositoryInput) GetInput() *IssueRepositoryInput { return v.Input }

// __CreateServiceInput is used internally by genqlient
type __CreateServiceInput struct {
	Input *ServiceInput `json:"input,omitempty"`
}

// GetInput returns __CreateServiceInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateServiceInput) GetInput() *ServiceInput { return v.Input }

// __CreateSupportGroupInput is used internally by genqlient
type __CreateSupportGroupInput struct {
	Input *SupportGroupInput `json:"input,omitempty"`
}

// GetInput returns __CreateSupportGroupInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateSupportGroupInput) GetInput() *SupportGroupInput { return v.Input }

// __ListComponentInstancesInput is used internally by genqlient
type __ListComponentInstancesInput struct {
	Filter *ComponentInstanceFilter `json:"filter,omitempty"`
}

// GetFilter returns __ListComponentInstancesInput.Filter, and is useful for accessing the field via an interface.
func (v *__ListComponentInstancesInput) GetFilter() *ComponentInstanceFilter { return v.Filter }

// __ListComponentVersionsInput is used internally by genqlient
type __ListComponentVersionsInput struct {
	Filter *ComponentVersionFilter `json:"filter,omitempty"`
}

// GetFilter returns __ListComponentVersionsInput.Filter, and is useful for accessing the field via an interface.
func (v *__ListComponentVersionsInput) GetFilter() *ComponentVersionFilter { return v.Filter }

// __ListComponentsInput is used internally by genqlient
type __ListComponentsInput struct {
	Filter *ComponentFilter `json:"filter,omitempty"`
	First  int              `json:"first"`
	After  string           `json:"after"`
}

// GetFilter returns __ListComponentsInput.Filter, and is useful for accessing the field via an interface.
func (v *__ListComponentsInput) GetFilter() *ComponentFilter { return v.Filter }

// GetFirst returns __ListComponentsInput.First, and is useful for accessing the field via an interface.
func (v *__ListComponentsInput) GetFirst() int { return v.First }

// GetAfter returns __ListComponentsInput.After, and is useful for accessing the field via an interface.
func (v *__ListComponentsInput) GetAfter() string { return v.After }

// __ListIssueRepositoriesInput is used internally by genqlient
type __ListIssueRepositoriesInput struct {
	Filter *IssueRepositoryFilter `json:"filter,omitempty"`
}

// GetFilter returns __ListIssueRepositoriesInput.Filter, and is useful for accessing the field via an interface.
func (v *__ListIssueRepositoriesInput) GetFilter() *IssueRepositoryFilter { return v.Filter }

// __ListIssuesInput is used internally by genqlient
type __ListIssuesInput struct {
	Filter *IssueFilter `json:"filter,omitempty"`
	First  int          `json:"first"`
}

// GetFilter returns __ListIssuesInput.Filter, and is useful for accessing the field via an interface.
func (v *__ListIssuesInput) GetFilter() *IssueFilter { return v.Filter }

// GetFirst returns __ListIssuesInput.First, and is useful for accessing the field via an interface.
func (v *__ListIssuesInput) GetFirst() int { return v.First }

// __ListServicesInput is used internally by genqlient
type __ListServicesInput struct {
	Filter *ServiceFilter `json:"filter,omitempty"`
}

// GetFilter returns __ListServicesInput.Filter, and is useful for accessing the field via an interface.
func (v *__ListServicesInput) GetFilter() *ServiceFilter { return v.Filter }

// __ListSupportGroupsInput is used internally by genqlient
type __ListSupportGroupsInput struct {
	Filter *SupportGroupFilter `json:"filter,omitempty"`
}

// GetFilter returns __ListSupportGroupsInput.Filter, and is useful for accessing the field via an interface.
func (v *__ListSupportGroupsInput) GetFilter() *SupportGroupFilter { return v.Filter }

// The query or mutation executed by AddComponentVersionToIssue.
const AddComponentVersionToIssue_Operation = `
mutation AddComponentVersionToIssue ($issueId: ID!, $componentVersionId: ID!) {
	addComponentVersionToIssue(issueId: $issueId, componentVersionId: $componentVersionId) {
		id
		primaryName
		description
		type
	}
}
`

func AddComponentVersionToIssue(
	ctx_ context.Context,
	client_ graphql.Client,
	issueId string,
	componentVersionId string,
) (*AddComponentVersionToIssueResponse, error) {
	req_ := &graphql.Request{
		OpName: "AddComponentVersionToIssue",
		Query:  AddComponentVersionToIssue_Operation,
		Variables: &__AddComponentVersionToIssueInput{
			IssueId:            issueId,
			ComponentVersionId: componentVersionId,
		},
	}
	var err_ error

	var data_ AddComponentVersionToIssueResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by AddServiceToSupportGroup.
const AddServiceToSupportGroup_Operation = `
mutation AddServiceToSupportGroup ($supportGroupId: ID!, $serviceId: ID!) {
	addServiceToSupportGroup(supportGroupId: $supportGroupId, serviceId: $serviceId) {
		id
		ccrn
	}
}
`

func AddServiceToSupportGroup(
	ctx_ context.Context,
	client_ graphql.Client,
	supportGroupId string,
	serviceId string,
) (*AddServiceToSupportGroupResponse, error) {
	req_ := &graphql.Request{
		OpName: "AddServiceToSupportGroup",
		Query:  AddServiceToSupportGroup_Operation,
		Variables: &__AddServiceToSupportGroupInput{
			SupportGroupId: supportGroupId,
			ServiceId:      serviceId,
		},
	}
	var err_ error

	var data_ AddServiceToSupportGroupResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by CreateComponent.
const CreateComponent_Operation = `
mutation CreateComponent ($input: ComponentInput!) {
	createComponent(input: $input) {
		id
		ccrn
		type
	}
}
`

func CreateComponent(
	ctx_ context.Context,
	client_ graphql.Client,
	input *ComponentInput,
) (*CreateComponentResponse, error) {
	req_ := &graphql.Request{
		OpName: "CreateComponent",
		Query:  CreateComponent_Operation,
		Variables: &__CreateComponentInput{
			Input: input,
		},
	}
	var err_ error

	var data_ CreateComponentResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by CreateComponentInstance.
const CreateComponentInstance_Operation = `
mutation CreateComponentInstance ($input: ComponentInstanceInput!) {
	createComponentInstance(input: $input) {
		id
		ccrn
		count
		componentVersionId
		serviceId
	}
}
`

func CreateComponentInstance(
	ctx_ context.Context,
	client_ graphql.Client,
	input *ComponentInstanceInput,
) (*CreateComponentInstanceResponse, error) {
	req_ := &graphql.Request{
		OpName: "CreateComponentInstance",
		Query:  CreateComponentInstance_Operation,
		Variables: &__CreateComponentInstanceInput{
			Input: input,
		},
	}
	var err_ error

	var data_ CreateComponentInstanceResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by CreateComponentVersion.
const CreateComponentVersion_Operation = `
mutation CreateComponentVersion ($input: ComponentVersionInput!) {
	createComponentVersion(input: $input) {
		id
		version
		componentId
	}
}
`

func CreateComponentVersion(
	ctx_ context.Context,
	client_ graphql.Client,
	input *ComponentVersionInput,
) (*CreateComponentVersionResponse, error) {
	req_ := &graphql.Request{
		OpName: "CreateComponentVersion",
		Query:  CreateComponentVersion_Operation,
		Variables: &__CreateComponentVersionInput{
			Input: input,
		},
	}
	var err_ error

	var data_ CreateComponentVersionResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by CreateIssue.
const CreateIssue_Operation = `
mutation CreateIssue ($input: IssueInput!) {
	createIssue(input: $input) {
		id
		primaryName
		description
		type
	}
}
`

func CreateIssue(
	ctx_ context.Context,
	client_ graphql.Client,
	input *IssueInput,
) (*CreateIssueResponse, error) {
	req_ := &graphql.Request{
		OpName: "CreateIssue",
		Query:  CreateIssue_Operation,
		Variables: &__CreateIssueInput{
			Input: input,
		},
	}
	var err_ error

	var data_ CreateIssueResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by CreateIssueRepository.
const CreateIssueRepository_Operation = `
mutation CreateIssueRepository ($input: IssueRepositoryInput!) {
	createIssueRepository(input: $input) {
		id
		name
		url
	}
}
`

func CreateIssueRepository(
	ctx_ context.Context,
	client_ graphql.Client,
	input *IssueRepositoryInput,
) (*CreateIssueRepositoryResponse, error) {
	req_ := &graphql.Request{
		OpName: "CreateIssueRepository",
		Query:  CreateIssueRepository_Operation,
		Variables: &__CreateIssueRepositoryInput{
			Input: input,
		},
	}
	var err_ error

	var data_ CreateIssueRepositoryResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by CreateService.
const CreateService_Operation = `
mutation CreateService ($input: ServiceInput!) {
	createService(input: $input) {
		id
		ccrn
	}
}
`

func CreateService(
	ctx_ context.Context,
	client_ graphql.Client,
	input *ServiceInput,
) (*CreateServiceResponse, error) {
	req_ := &graphql.Request{
		OpName: "CreateService",
		Query:  CreateService_Operation,
		Variables: &__CreateServiceInput{
			Input: input,
		},
	}
	var err_ error

	var data_ CreateServiceResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by CreateSupportGroup.
const CreateSupportGroup_Operation = `
mutation CreateSupportGroup ($input: SupportGroupInput!) {
	createSupportGroup(input: $input) {
		id
		ccrn
	}
}
`

func CreateSupportGroup(
	ctx_ context.Context,
	client_ graphql.Client,
	input *SupportGroupInput,
) (*CreateSupportGroupResponse, error) {
	req_ := &graphql.Request{
		OpName: "CreateSupportGroup",
		Query:  CreateSupportGroup_Operation,
		Variables: &__CreateSupportGroupInput{
			Input: input,
		},
	}
	var err_ error

	var data_ CreateSupportGroupResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ListComponentInstances.
const ListComponentInstances_Operation = `
query ListComponentInstances ($filter: ComponentInstanceFilter) {
	ComponentInstances(filter: $filter) {
		totalCount
		edges {
			node {
				id
			}
		}
	}
}
`

func ListComponentInstances(
	ctx_ context.Context,
	client_ graphql.Client,
	filter *ComponentInstanceFilter,
) (*ListComponentInstancesResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListComponentInstances",
		Query:  ListComponentInstances_Operation,
		Variables: &__ListComponentInstancesInput{
			Filter: filter,
		},
	}
	var err_ error

	var data_ ListComponentInstancesResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ListComponentVersions.
const ListComponentVersions_Operation = `
query ListComponentVersions ($filter: ComponentVersionFilter) {
	ComponentVersions(filter: $filter) {
		edges {
			node {
				id
				version
				componentId
			}
		}
	}
}
`

func ListComponentVersions(
	ctx_ context.Context,
	client_ graphql.Client,
	filter *ComponentVersionFilter,
) (*ListComponentVersionsResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListComponentVersions",
		Query:  ListComponentVersions_Operation,
		Variables: &__ListComponentVersionsInput{
			Filter: filter,
		},
	}
	var err_ error

	var data_ ListComponentVersionsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ListComponents.
const ListComponents_Operation = `
query ListComponents ($filter: ComponentFilter, $first: Int, $after: String) {
	Components(filter: $filter, first: $first, after: $after) {
		totalCount
		edges {
			node {
				id
				ccrn
				type
				componentVersions {
					edges {
						node {
							id
							version
							componentId
						}
					}
				}
			}
			cursor
		}
	}
}
`

func ListComponents(
	ctx_ context.Context,
	client_ graphql.Client,
	filter *ComponentFilter,
	first int,
	after string,
) (*ListComponentsResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListComponents",
		Query:  ListComponents_Operation,
		Variables: &__ListComponentsInput{
			Filter: filter,
			First:  first,
			After:  after,
		},
	}
	var err_ error

	var data_ ListComponentsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ListIssueRepositories.
const ListIssueRepositories_Operation = `
query ListIssueRepositories ($filter: IssueRepositoryFilter) {
	IssueRepositories(filter: $filter) {
		totalCount
		edges {
			node {
				id
			}
		}
	}
}
`

func ListIssueRepositories(
	ctx_ context.Context,
	client_ graphql.Client,
	filter *IssueRepositoryFilter,
) (*ListIssueRepositoriesResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListIssueRepositories",
		Query:  ListIssueRepositories_Operation,
		Variables: &__ListIssueRepositoriesInput{
			Filter: filter,
		},
	}
	var err_ error

	var data_ ListIssueRepositoriesResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ListIssues.
const ListIssues_Operation = `
query ListIssues ($filter: IssueFilter, $first: Int) {
	Issues(filter: $filter, first: $first) {
		edges {
			node {
				id
				primaryName
				description
				type
			}
		}
	}
}
`

func ListIssues(
	ctx_ context.Context,
	client_ graphql.Client,
	filter *IssueFilter,
	first int,
) (*ListIssuesResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListIssues",
		Query:  ListIssues_Operation,
		Variables: &__ListIssuesInput{
			Filter: filter,
			First:  first,
		},
	}
	var err_ error

	var data_ ListIssuesResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ListServices.
const ListServices_Operation = `
query ListServices ($filter: ServiceFilter) {
	Services(filter: $filter) {
		totalCount
		edges {
			node {
				id
			}
		}
	}
}
`

func ListServices(
	ctx_ context.Context,
	client_ graphql.Client,
	filter *ServiceFilter,
) (*ListServicesResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListServices",
		Query:  ListServices_Operation,
		Variables: &__ListServicesInput{
			Filter: filter,
		},
	}
	var err_ error

	var data_ ListServicesResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ListSupportGroups.
const ListSupportGroups_Operation = `
query ListSupportGroups ($filter: SupportGroupFilter) {
	SupportGroups(filter: $filter) {
		totalCount
		edges {
			node {
				id
			}
		}
	}
}
`

func ListSupportGroups(
	ctx_ context.Context,
	client_ graphql.Client,
	filter *SupportGroupFilter,
) (*ListSupportGroupsResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListSupportGroups",
		Query:  ListSupportGroups_Operation,
		Variables: &__ListSupportGroupsInput{
			Filter: filter,
		},
	}
	var err_ error

	var data_ ListSupportGroupsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
