// Code generated by go generate; DO NOT EDIT.
package cache

import "context"

func WrapContext1[A1 any, R any](
	ctx context.Context,
	f func(context.Context, A1) (R, error),
) func(A1) (R, error) {
	return func(a1 A1) (R, error) {
		return f(ctx, a1)
	}
}

func WrapContext2[A1 any, A2 any, R any](
	ctx context.Context,
	f func(context.Context, A1, A2) (R, error),
) func(A1, A2) (R, error) {
	return func(a1 A1, a2 A2) (R, error) {
		return f(ctx, a1, a2)
	}
}

func WrapContext3[A1 any, A2 any, A3 any, R any](
	ctx context.Context,
	f func(context.Context, A1, A2, A3) (R, error),
) func(A1, A2, A3) (R, error) {
	return func(a1 A1, a2 A2, a3 A3) (R, error) {
		return f(ctx, a1, a2, a3)
	}
}

func WrapContext4[A1 any, A2 any, A3 any, A4 any, R any](
	ctx context.Context,
	f func(context.Context, A1, A2, A3, A4) (R, error),
) func(A1, A2, A3, A4) (R, error) {
	return func(a1 A1, a2 A2, a3 A3, a4 A4) (R, error) {
		return f(ctx, a1, a2, a3, a4)
	}
}

func WrapContext5[A1 any, A2 any, A3 any, A4 any, A5 any, R any](
	ctx context.Context,
	f func(context.Context, A1, A2, A3, A4, A5) (R, error),
) func(A1, A2, A3, A4, A5) (R, error) {
	return func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5) (R, error) {
		return f(ctx, a1, a2, a3, a4, a5)
	}
}

func WrapContext6[A1 any, A2 any, A3 any, A4 any, A5 any, A6 any, R any](
	ctx context.Context,
	f func(context.Context, A1, A2, A3, A4, A5, A6) (R, error),
) func(A1, A2, A3, A4, A5, A6) (R, error) {
	return func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) (R, error) {
		return f(ctx, a1, a2, a3, a4, a5, a6)
	}
}

func WrapContext7[A1 any, A2 any, A3 any, A4 any, A5 any, A6 any, A7 any, R any](
	ctx context.Context,
	f func(context.Context, A1, A2, A3, A4, A5, A6, A7) (R, error),
) func(A1, A2, A3, A4, A5, A6, A7) (R, error) {
	return func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) (R, error) {
		return f(ctx, a1, a2, a3, a4, a5, a6, a7)
	}
}

func WrapContext8[A1 any, A2 any, A3 any, A4 any, A5 any, A6 any, A7 any, A8 any, R any](
	ctx context.Context,
	f func(context.Context, A1, A2, A3, A4, A5, A6, A7, A8) (R, error),
) func(A1, A2, A3, A4, A5, A6, A7, A8) (R, error) {
	return func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) (R, error) {
		return f(ctx, a1, a2, a3, a4, a5, a6, a7, a8)
	}
}

func WrapContext9[A1 any, A2 any, A3 any, A4 any, A5 any, A6 any, A7 any, A8 any, A9 any, R any](
	ctx context.Context,
	f func(context.Context, A1, A2, A3, A4, A5, A6, A7, A8, A9) (R, error),
) func(A1, A2, A3, A4, A5, A6, A7, A8, A9) (R, error) {
	return func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) (R, error) {
		return f(ctx, a1, a2, a3, a4, a5, a6, a7, a8, a9)
	}
}

func WrapContext10[A1 any, A2 any, A3 any, A4 any, A5 any, A6 any, A7 any, A8 any, A9 any, A10 any, R any](
	ctx context.Context,
	f func(context.Context, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) (R, error),
) func(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10) (R, error) {
	return func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9, a10 A10) (R, error) {
		return f(ctx, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10)
	}
}
