name: CI and E2E Testing

on: [pull_request]
#on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26'
          cache: true        # Cache go.sum dependencies

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          cache: 'pip'           # Cache pip packages
          cache-dependency-path: 'e2e/requirements.txt'

      - name: Install E2E Python dependencies
        run: make e2e

      # Buildx (used for fast caching of docker layers)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build UI Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./ui
          file: ./ui/Dockerfile
          push: false
          load: true # Load image from local docker daemon on GHA
          tags: ui-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run BE and DB
        run: |
          make compose-up
          sleep 10

      - name: Run E2E Tests
        working-directory: ./e2e
        run: |
          make TAG=xxx test
