name: Release

on:
  push:
    branches:
      - main
    paths:
      - cmd/**
      - scanner/**
      - internal/**
      - pkg/**
      - go.mod
      - go.sum

jobs:
  release:
    name: Semantic Release
    runs-on: default
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Create VERSION file if it doesn't exist
        run: |
          if [ ! -f VERSION ]; then
            echo "0.0.0" > VERSION
          fi

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release